import json
import re

items = [
    ("1.1. Trang bị đồng bộ", [
        ("Bộ điều khiển ga", "1b"),
        ("Cụm ống xả", "1"),
        ("Tấm che ống xả", "1"),
        ("Cụm ống hút", "1"),
        ("Nắp đậy BR cam cơ", "2"),
        ("Nắp đậy dàn cò mổ", "1"),
        ("Nắp đổ nhớt", "1"),
        ("Thước đo nhớt", "1"),
        ("Lọc nhớt", "1"),
        ("Cụm cánh bướm ga", "1"),
        ("Đường ống xăng", "1b"),
        ("Cánh quạt", "1"),
        ("Bát bắt máy phát+tăngđưa", "1"),
        ("Bát câu máy", "2"),
        ("Puly trục cơ", "1"),
        ("Puly bơm nước", "1"),
        ("Cạc te động cơ", "1"),
        ("Chân máy", "2"),
        ("Phe gài chốt", "4"),
        ("Vòng găng", "4b"),
        ("Tay biên", "4"),
        ("Bạc thau tay biên", "4"),
        ("Xilanh", "4"),
        ("Thân máy", "1"),
        ("Cổ nước đi về", "2"),
        ("Tấm dừng bánh đà", "1"),
        ("Puly tăng đưa curoa", "1"),
        ("Bát bắt máy nén", "1")
    ]),
    ("1.2. Cụm – chi tiết", [
        ("Ống hút + hồi nhiên liệu", "1b"),
        ("Van điều chỉnh AS kim phun", "1b"),
        ("Kim phun", "4b"),
        ("Bơm xăng", "1b"),
        ("Bơm nước", "1b"),
        ("Bơm nhớt", "1b"),
        ("Bộ biến mô", "1b"),
        ("Bánh đà + vành răng", "1b"),
        ("Nắp máy", "1b"),
        ("Xu páp xả + hút", "8"),
        ("Ống dẫn hướng XP", "8"),
        ("Lò xo xu páp + đế LX", "8b"),
        ("Chén chặn xu páp", "8"),
        ("Móng hãm xu páp", "16"),
        ("Con đội", "8"),
        ("Trục cam", "1"),
        ("Ổ đỡ trục cam", "1b"),
        ("Dây đai cam", "1"),
        ("Bánh răng cam-cơ", "1+1"),
        ("Trục cơ", "1"),
        ("Bạc cổ chính + biên", "2b"),
        ("Vòng bi trục cơ", "1"),
        ("Piston", "4"),
        ("Chốt piston", "4"),
        ("Cụm tốc độ + dây", "1")
    ]),
    ("2- HỆ THỐNG ĐIỆN", [
        ("Máy khởi động", "1"),
        ("Bạc thau", "3"),
        ("Than khởi động + giá", "1b"),
        ("Đầu nê khởi động", "1"),
        ("Bánh răng khởi động", "1"),
        ("Rờ le khởi động", "1"),
        ("Modun đánh lửa", "2"),
        ("Nến điện", "4"),
        ("Chụp nến điện", "4"),
        ("Dây phin", "4"),
        ("Máy phát điện", "1b"),
        ("Puly máy phát", "1"),
        ("Bi máy phát", "2"),
        ("Than máy phát", "1b"),
        ("Vỉ tiết chế", "1"),
        ("Rơ le đề phụ", "1"),
        ("Bình điện", "1"),
        ("Cọc bình điện", "2"),
        ("Cáp mát ( - )", "1"),
        ("Cáp lửa ( + )", "1"),
        ("Đồng hồ điện báo đèn", "1"),
        ("AS nhớt báo đèn", "1"),
        ("tO nước", "1"),
        ("nhiên liệu", "1"),
        ("tốc độ", "1"),
        ("tốc độ vòng tua máy", "1"),
        ("Bóng đèn đồng hồ", "1b"),
        ("Tay gạt xi nhan", "1"),
        ("Công tắc điện", "1"),
        ("gạt mưa", "1"),
        ("rửa kính", "1"),
        ("đèn trung tâm", "1"),
        ("đèn pha chính", "1"),
        ("đèn khoang xe", "1"),
        ("đèn khoang lái", "1"),
        ("Buton nhấn còi", "1"),
        ("Còi điện", "2"),
        ("Máy gạt mưa", "1b"),
        ("Bộ thanh chuyền", "1b"),
        ("Cần gạt mưa", "2"),
        ("Chổi gạt mưa", "2"),
        ("Cụm tay gạt mưa", "1b"),
        ("Bộ rửa kính", "1"),
        ("Bầu nước rửa kính", "1"),
        ("Đèn pha", "2"),
        ("hiệu trước + Đèn cản", "2+2"),
        ("hiệu sau", "2"),
        ("hiệu hông", "2"),
        ("số de", "2"),
        ("soi biển số", "2"),
        ("khoang xe", "2"),
        ("Bơm xăng điện", "1b"),
        ("ECU", "1b"),
        ("Càm biến vị trí trục cơ", "1"),
        ("vị trí Tr/cam", "1"),
        ("vị trí bướm ga", "1"),
        ("lưu lượng khí nạp", "1"),
        ("tO nước", "1"),
        ("AS nhớt", "1"),
        ("Cầu chì các loại", "1b"),
        ("Rờ le các loại", "1b"),
        ("Bộ dây điện", "1b")
    ]),
    ("3- HỆ THỐNG LÁI", [
        ("Vành tay lái", "1"),
        ("Nhấn còi", "1"),
        ("Ống tay lái", "1"),
        ("Trục tay lái", "1"),
        ("Cardan lái", "1"),
        ("Chữ thập cardan", "2"),
        ("Bơm trợ lực lái", "1b"),
        ("Van chia dầu lái", "1"),
        ("Bost lái", "1"),
        ("Trục vít", "1"),
        ("Trục rẻ quạt(C/ngang)", "1"),
        ("Bi trục vít", "1b"),
        ("Bi trục rẻ quạt", "1b"),
        ("Bi trục tay lái", "1"),
        ("Bạc thau hộp tay lái", "1"),
        ("Rô tuyn chuyển hướng", "4"),
        ("Thanh chuyển hướng", "2b")
    ]),
    ("4- HỆ THỐNG PHANH", [
        ("Bơm phanh cái", "1"),
        ("Lúp pê bơm phanh", "1"),
        ("Bầu chứa dầu phanh", "1"),
        ("Bầu trợ lực", "1"),
        ("Bơm phanh con sau", "2"),
        ("Bơm phanh con trước", "2"),
        ("Đĩa-Tang trống phanh trước", "2"),
        ("Đĩa-Tang trống phanh sau", "2"),
        ("Guốc-Má phanh trước +sau", "8"),
        ("Lò xo guốc phanh", "1b"),
        ("Tấm dừng bánh xe", "4"),
        ("Đường ống phanh", "1b"),
        ("Tay kéo phanh", "1"),
        ("Bộ cáp kéo phanh", "1b"),
        ("Cụm chỉnh phanh", "1b")
    ]),
    ("5- HỘP SỐ", [
        ("Cần số chính", "1"),
        ("Vỏ hộp số", "1"),
        ("Nắp hộp số", "1"),
        ("Bộ biến mô", "1b"),
        ("Trục biến mô", "1"),
        ("Bộ bánh răng hành tinh 1", "1b"),
        ("Bộ bánh răng hành tinh 2", "1b"),
        ("Bộ bánh răng hành tinh 3", "1b"),
        ("Bộ bánh răng hành tinh 4", "1b"),
        ("Trục vào hộp số", "1b"),
        ("Trục ra hộp số", "1b"),
        ("Trục bánh răng trung gian", "1b"),
        ("Bộ ly hợp 1", "1"),
        ("Bộ ly hợp 2", "1"),
        ("Bộ ly hợp 3", "1"),
        ("Bộ ly hợp 4", "1"),
        ("Bộ ly hợp 5", "1"),
        ("Bộ ly hợp tiến", "1"),
        ("Cacte hộp số", "1"),
        ("Bơm dầu hộp số", "1"),
        ("Van điện từ điều khiển", "3")
    ]),
    ("6- CẦU TRƯỚC", [
        ("Bán trục + khớp xoay", "2b")
    ]),
    ("7- DẦM CẦU SAU", [
        ("Bán trục (láp ngang)", "2"),
        ("đùm", "2"),
        ("Mâm bánh xe", "2"),
        ("May ơ bánh xe", "2"),
        ("Gudông tắc kê", "12b")
    ]),
    ("8- HÊ THỐNG TREO", [
        ("Ống giảm xóc phía trước", "2"),
        ("Giàn chữ A", "2"),
        ("Bát đỡ ống giảm xóc", "2"),
        ("Rô tuyn trụ", "2b"),
        ("Rô tuyn thanh giằng", "2"),
        ("Ống giảm xóc phía sau", "2"),
        ("Lò xo giảm chấn", "2"),
        ("Đòn treo sau + cao su", "2b"),
        ("Thanh giằng sau", "1b")
    ]),
    ("9- CA BIN, THÂN XE", [
        ("Kính chắn gió", "1"),
        ("Kính chiếu hậu ngoài", "2"),
        ("Tay kính chiếu hậu ngoài", "2"),
        ("Mặt nạ", "1"),
        ("Khóa gài cabô", "1b"),
        ("Chống cabô", "1b"),
        ("Tay mở cửa cabô trong", "1"),
        ("Bệ táp lô nhựa cabin", "1b"),
        ("Cửa hông xe", "4b"),
        ("Tấm che trong cửa hông", "4"),
        ("Kính cửa hông", "4"),
        ("Cơ cấu quay kính", "4"),
        ("Tay quay kính", "4"),
        ("Tay nắm trong cửa", "4"),
        ("Cơ cấu khóa cửa", "4"),
        ("Tay mở cửa ngoài", "4"),
        ("Tay mở cửa trong", "4"),
        ("Ty đẩy cốp", "2"),
        ("Cơ cấu khóa cốp", "1b"),
        ("Tấm che trong cửa cốp", "1"),
        ("Tay mở ngoài cốp", "1"),
        ("Ổ khóa chìa", "3")
    ]),
    ("10- TRANG BỊ ĐỒNG BỘ", [
        ("Két nước + nắp", "1b"),
        ("Bọc gió két nước", "1"),
        ("Lọc gió + ruột", "1b"),
        ("Cao su lọc gió", "1"),
        ("Thùng nhiên liệu + nắp", "1"),
        ("Phao xăng", "1b"),
        ("Lọc nhiên liệu sơ cấp", "1"),
        ("Bô giảm thanh + ống xả", "1b"),
        ("Cao su chắn bùn T+ S", "4"),
        ("Giá lốp dự phòng", "1b"),
        ("Lốp dự phòng", "1b")
    ]),
    ("11- NỘI THẤT", [
        ("La phông trần (nỉ)", "1b"),
        ("Bọc thành trong + cửa", "1b"),
        ("Tấm che nắng", "2"),
        ("Bộ đệm ghế", "04"),
        ("Khung ghế", "04"),
        ("Táp bi trải sàn", "1b"),
        ("Đệm giảm âm ca bô", "1b"),
        ("Đệm chống nóng cabô", "1"),
        ("Gioăng viền cửa", "4"),
        ("Gioăng viền cốp sau", "1"),
        ("Gioăng kính hông", "4"),
        ("Gioăng kính chắn gió", "4"),
        ("Gioăng kính sau", "1")
    ]),
    ("12- KHUNG XE", [
        ("Biển số", "2"),
        ("Cản trước (nhựa)", "1b"),
        ("Bát móc kéo trước", "2"),
        ("Cản sau (nhựa)", "1"),
        ("Vòng móc kéo sau", "1")
    ]),
    ("13- HỆ THỐNG LẠNH", [
        ("Máy nén", "1"),
        ("Két dàn nóng", "1"),
        ("Khung bảo vệ két DN", "1"),
        ("Quạt giàn nóng", "1"),
        ("Ống dàn lạnh", "4"),
        ("Ống thổi gió dàn lạnh", "5"),
        ("Rờ le nhiệt độ", "2"),
        ("Van tiết lưu", "1"),
        ("Timer start", "1"),
        ("Phin + lọc ga", "1b")
    ]),
    ("14- HỆ THỐNG ÂM THANH", [
        ("Ang ten nóc xe", "1"),
        ("Catsett", "1b")
    ]),
    ("15- TRANG BỊ KHÁC", [
        ("Lốp bánh xe", "4b"),
        ("Lốp dự phòng", "1b"),
        ("Giá lốp dự phòng", "1b")
    ])
]

output = {
    "templateVersion": 1,
    "vehicleCode": "CHEVROLET-SELECT",
    "vehicleName": "Chevrolet",
    "protocolType": "KIEM_CHON",
    "sections": []
}

total_items = 0
for sec_name, sec_items in items:
    section = {"name": sec_name, "items": []}
    for item_name, quantity in sec_items:
        clean_name = re.sub(r'^\s*-\s*', '', item_name)
        clean_name = re.sub(r'^\d+\s*\.?\s*', '', clean_name)
        section["items"].append({
            "name": clean_name,
            "quantity": quantity
        })
        total_items += 1
    output["sections"].append(section)

print(f"Total items extracted: {total_items}")

with open("src/templates/selections/ChevroletSelection.json", "w", encoding="utf-8") as f:
    json.dump(output, f, ensure_ascii=False, indent=2)

