import json
import re

items = [
    ("1.1- TRANG BỊ NGOÀI", [
        ("Cụm van tắt máy", "1"),
        ("Bộ Đ/khiển ga BCA", "1b"),
        ("Nắp đậy dàn cò mổ", "2"),
        ("Cụm ống xả", "2"),
        ("Cụm ống hút", "2"),
        ("Bộ nắp đậy đầu máy", "1b"),
        ("Ống hút ngang + cổ", "1b"),
        ("Ống nước nắp máy", "3"),
        ("Cổ ốngnước trêndưới", "2"),
        ("Ống nước ngang", "1"),
        ("Ống nước từ bơm lên", "1"),
        ("Ống thoát hơi máy", "1"),
        ("Nắp đổ nhớt", "1"),
        ("Ống đổ nhớt", "1"),
        ("Thước đo nhớt + vỏ", "1b"),
        ("Lọc nhớt ly tâm (tinh)", "1b"),
        ("Lọc nhớt thô", "1b"),
        ("Đườngốngnhớtrắcco", "1b"),
        ("Lọc nhiên liệu", "2"),
        ("Bát bắt lọc N/liệu", "1"),
        ("ĐườngốngNL+rắcco", "1b"),
        ("Bát máy phát", "1"),
        ("Bát câu máy", "2"),
        ("Cánh quạt gió", "1"),
        ("Bích bắt quạt gió", "1"),
        ("Puly quạt gió", "1"),
        ("Puly bơm nước", "1"),
        ("Puly trục cơ", "1"),
        ("Puly tăng đưa + bát", "1b"),
        ("Khóa nước thân máy", "2"),
        ("Khóa nhớt", "1"),
        ("Vỏ bọc bánh đà", "1"),
        ("Cạc te động cơ", "1"),
        ("Tấm che dưới ly hợp", "1"),
        ("Chân máy", "1b"),
        ("Ống cao áp", "6"),
        ("Ống dầu hồi", "1b")
    ]),
    ("1.2- CỤM – CHI TIẾT", [
        ("Bơm cao áp", "1b"),
        ("Bộ đôi ty bơm CA", "6"),
        ("Trục cam", "1"),
        ("Con đội", "6"),
        ("Vòng răng", "6"),
        ("Chén chặn", "6"),
        ("Lò xo", "6"),
        ("Van 1 chiều", "1"),
        ("Bộ điều tốc", "1"),
        ("Bộ phun sớm", "1"),
        ("Thước ga", "1"),
        ("Bơm thấp áp (bơmtay", "1b"),
        ("Bộ dẫn động BCA", "1b"),
        ("Trục dẫn động BCA", "1"),
        ("Mặt bích dẫn động", "2"),
        ("Kim phun", "6b"),
        ("Đầu kim phun", "6"),
        ("Quạt tăng áp", "2b"),
        ("Bơm nhớt", "1b"),
        ("Bích giữa nắp &thân", "1"),
        ("Trục chủ động", "1"),
        ("Trục bị động", "1"),
        ("Bánh răng", "2"),
        ("Bơm nước", "1b"),
        ("Cổ ống nước bơm", "1"),
        ("Trục bơm", "1"),
        ("Guồng bơm", "1"),
        ("Bộ phớt phíp", "1"),
        ("Cụm D/động Q/gió", "1b"),
        ("Bích bắt cánh quạt", "1"),
        ("Trục quạt gió", "1"),
        ("Cánh xoắn", "1"),
        ("Ổ đỡ đầu trục cam", "1"),
        ("Đệm chặn trục cam", "1"),
        ("Bánh răng cam - cơ", "1.b"),
        ("B/răng trung gian", "1"),
        ("B/răng D/động BCA", "1"),
        ("B/răng D/độngQ/gió", "1"),
        ("Bơm hơi", "1b"),
        ("Van điều tiết áp suất", "1"),
        ("Ốngnhớt+rắc coB/hơi", "1b"),
        ("Ongnước,rắc coB/hơi", "1b"),
        ("Nắp cửa hút khí vào", "1"),
        ("Trục cơ", "1"),
        ("Bánh răng trục cơ", "1"),
        ("Tay biên", "2"),
        ("Bạc biên", "1b"),
        ("Piston, chốt, V/găng", "2b"),
        ("Xi lanh", "2"),
        ("Lò xo van 1 chiều", "2"),
        ("Van 1 chiều", "2"),
        ("Bộ ly hợp", "1b"),
        ("Đĩa ép", "1"),
        ("Đĩa ép trung gian", "1"),
        ("Vòng tì", "1"),
        ("Cần bẩy", "4"),
        ("Lò xo đĩa ép", "1b"),
        ("Đĩa thép ma sát", "2"),
        ("Bố ma sát", "4"),
        ("Bánh đà", "1"),
        ("Vành răng bánh đà", "1"),
        ("Nắp máy", "6"),
        ("Trục cò mổ", "6"),
        ("Cò mổ", "12"),
        ("Bạc cò mổ", "12"),
        ("Xu páp hút + xả", "6+6"),
        ("Miệng xie XP hút+xả", "6+6"),
        ("Ống D/hướng xupáp", "12"),
        ("Lò xo xu páp", "24"),
        ("Đế lò xo", "12"),
        ("Chén chặn xu páp", "12"),
        ("Móng hãm xu páp", "24"),
        ("Đũa đẩy", "12"),
        ("Con đội", "12"),
        ("Trục cam ( cote :", "1"),
        ("Bạc đầu nhỏ Tr/cam", "1"),
        ("Bạc trục cam", "1b"),
        ("Trục cơ ( cote :", "1"),
        ("Bạc cổ chính", "1b"),
        ("Bạc cổ biên", "1b"),
        ("Đệm dọc trục", "2"),
        ("Vòng chặn nhớt T+ S", "2"),
        ("Bích chặn trục cơ", "1"),
        ("Piston ( cote :", "6"),
        ("Chốt piston", "6"),
        ("Phe gài chốt", "12"),
        ("Vòng găng", "6b"),
        ("Tay biên", "6"),
        ("Bạc thau tay biên", "6"),
        ("Xilanh ( cote :", "6"),
        ("Thân máy", "1")
    ]),
    ("*- Vòng bi động cơ các loại", [
        ("Vòng bi 1180304.K1", "1"),
        ("Vòng bi 1160305.K1", "1"),
        ("Vòng bi 6203", "1"),
        ("Vòng bi 30204", "2"),
        ("Vòng bi 6006.Z", "1"),
        ("Vòng bi 6201-2RS", "2"),
        ("Vòng bi 6207 B/hơi", "2"),
        ("Vòng bi 6014", "1"),
        ("Vòng bi 6305", "2"),
        ("Vòng bi 6204", "1"),
        ("Vòng bi 6205", "1")
    ]),
    ("1.3- TRANG BỊ ĐIỆN ĐỘNG CƠ", [
        ("Máy khởi động", "1b"),
        ("Bạc thau + than KĐ", "2b"),
        ("Đầu nê khởi động", "1"),
        ("Bánh răng khởi động", "1"),
        ("Rờ le khởi động", "1"),
        ("Than khởi động", "1b"),
        ("Cảm biến tO nước", "1"),
        ("AS nhớt", "1")
    ]),
    ("2- HỆ THỐNG ĐIỆN", [
        ("Máy phát điện 24v...", "1b"),
        ("Puly máy phát", "1"),
        ("Bi máy phát 180603", "1"),
        ("Bi máy phát 180502", "1"),
        ("Than máy phát", "2"),
        ("Vỉ tiết chế", "1"),
        ("Tiết chế", "1"),
        ("Rờ le đề phụ", "1"),
        ("Bình điện", "2"),
        ("Cọc bình điện", "2"),
        ("Cáp mát", "1"),
        ("Cáp lửa", "1"),
        ("Đồng hồ điện", "1"),
        ("Đồng hồ AS nhớt", "1"),
        ("tO nước", "1"),
        ("hơi", "1"),
        ("nhiên liệu", "1"),
        ("tốc độ máy", "1"),
        ("tốc độ xe", "1"),
        ("Bộ điện báo tốc độ", "1"),
        ("Đuôi đèn đồng hồ", "5"),
        ("Tay gạt xi nhan, đèn TH", "1"),
        ("Tay gạt mưa TH", "1"),
        ("Công tắc điện", "1"),
        ("đèn trần", "3"),
        ("đèn rọi", "1"),
        ("đèn mui", "1"),
        ("10A(2nấc,3nấc)", "1"),
        ("cúp bình", "1"),
        ("Rờ le cúp bình", "1"),
        ("Buton nhấn còi", "1"),
        ("Còi điện", "1"),
        ("Còi hơi + Đạp còi hơi", "1+1"),
        ("Rờ le còi hơi", "1"),
        ("Máy gạt mưa", "1"),
        ("Cần gạt mưa", "3"),
        ("Chổi gạt mưa", "3"),
        ("Đèn pha", "2b"),
        ("Chóa đèn pha", "2"),
        ("Vành đèn pha", "2"),
        ("Bóng đèn pha", "2"),
        ("Đèn hiệu trước", "2"),
        ("Đèn hiệu sau", "2"),
        ("kích thước(xynhan)", "2"),
        ("Đèn cản vuông", "2"),
        ("đèn trần", "1"),
        ("đèn mui", "2"),
        ("biển số", "1"),
        ("hông ( LED)", "6"),
        ("sau thùng tròn", "2"),
        ("Cục chớp", "1"),
        ("stop hơi", "1"),
        ("Vú báo de+ Còi báo de", "1+1"),
        ("gài cầu", "1"),
        ("đèn AS nhớt", "1"),
        ("Bộ dây điện", "1b"),
        ("Bơm +béc + bầu nước", "1b")
    ]),
    ("3- HỆ THỐNG LÁI", [
        ("Vành TL (nhấn còi……", "1b"),
        ("Ống + bi ống tay lái", "1b"),
        ("Trục tay lái", "1"),
        ("Hộp cơ cấu lái", "1b"),
        ("Trục rẻ quạt (C/ngang", "1"),
        ("Bạc trục rẻ quạt ………", "1b"),
        ("Trục vít", "1"),
        ("Piston thanh răng", "1"),
        ("Vòng găng HTL", "1b"),
        ("Bi đầu trục vít …………", "2"),
        ("Bơm trợ lực lái", "1b"),
        ("Bánh răng dẫn động", "1b"),
        ("Bộ ruột bơm TL lái", "1"),
        ("Bi bơm TL lái", "2"),
        ("Bình dầu bơm TL lái", "1"),
        ("Van chia dầu lái", "1"),
        ("Khớp nối trục tay lái", "1"),
        ("Đòn quay đứng", "1"),
        ("ThanhCH ngang+dọc", "2"),
        ("Rô tuyn CH ngang", "2"),
        ("Rô tuyn CH dọc", "2"),
        ("Két mát nhớt lái", "1"),
        ("Ống dầu lái", "1b")
    ]),
    ("4- HỆ THỐNG PHANH", [
        ("Cụm bàn đạp", "1b"),
        ("Tổng phanh 2 tầng", "1"),
        ("Bầu phanh phụ sau", "2"),
        ("Bầu phanh phụ trước", "2"),
        ("Giá bầu phanh phụ", "4"),
        ("Cam phanh", "4"),
        ("Giá đỡ cam phanh", "4"),
        ("Rẻ quạt", "4"),
        ("Bầu hơi", "5"),
        ("Van an toàn", "1"),
        ("Van xả", "5"),
        ("Tang trống bánh xe", "4"),
        ("Tấm che tang trống", "4"),
        ("Guốc phanh chân", "6"),
        ("Lò xo guốc phanh", "4"),
        ("Tấm dừng bánh xe", "4"),
        ("Đường ống phanh", "1b"),
        ("Bộ điều hòa lực phanh", "1"),
        ("Chia hơi 5 ngã", "1"),
        ("VanĐ/khiển phanh tay", "1b"),
        ("Bộ làm mát hơi", "1"),
        ("Van chia hơi 2 tầng", "1"),
        ("Xy lanh hơi tắt máy", "2"),
        ("Cục đạp tắt máy", "1")
    ]),
    ("5-DẪN ĐỘNG LY HỢP", [
        ("Cụm bàn đạp", "1b"),
        ("Bi tê", "1"),
        ("Ổ trượt bi tê", "1"),
        ("Càng ngắt ly hợp", "1"),
        ("Bơm ly hợp + Bình dầu", "1+1"),
        ("Bộ trợ lực hơi ly hợp", "1")
    ]),
    ("6.1- HỘP SỐ CHÍNH", [
        ("Cần số chính", "1"),
        ("Công tắc gài nhanh chậm", "1b"),
        ("Rô tuyn gài số", "4"),
        ("Loa kèn", "1"),
        ("Đầu nối láp (đầu sáp", "1"),
        ("Nắp hộp số", "1"),
        ("Trục + Càng sang số", "3b"),
        ("Trục sơ cấp", "1"),
        ("Bộ đồng tốc 2 – 3", "1"),
        ("Bộ đồng tốc 4 – 5", "1"),
        ("Trục thứ cấp", "1"),
        ("Bánh răng", "1"),
        ("Trục trung gian", "1"),
        ("Bánh răng", "1"),
        ("Trục số de", "1"),
        ("Bánh răng số de", "1"),
        ("Bi ống rô lê", "1"),
        ("Bi số de", "2"),
        ("Vòng bi 292213", "1"),
        ("Vòng bi", "1"),
        ("Vòng bi", "1"),
        ("Bộ căn phe", "1b")
    ]),
    ("HỘP SỐ PHỤ", [
        ("Vỏ hộp số", "1"),
        ("Nắp hộp số", "11"),
        ("Trục+ càng gài C - S", "2b"),
        ("Trục sơ cấp", "1"),
        ("B/răng số 1, 2 TSC", "1"),
        ("Trục trung gian", "1"),
        ("B/răng số 1,2TTG", "1"),
        ("Trục thứ cấp (ra sau)", "1"),
        ("B/răng trục thứ cấp", "1"),
        ("Trục ra cầu trước", "1"),
        ("B/răng trục ra cầu T", "1"),
        ("Đầu sáp trục SC-T-S", "3"),
        ("Bánh+ trục vít tốc độ", "1b"),
        ("Bộ căn phe", "1")
    ]),
    ("7.1-CARDAN CHÍNH", [
        ("Đầu then trong", "1"),
        ("Đầu then ngoài", "1"),
        ("Chữ thập đồng bộ", "2"),
        ("Chạc trục truyền CD", "2"),
        ("Nắp che bụi thân CD", "1")
    ]),
    ("7.2-CARDAN TRƯỚC", [
        ("Đầu then trong", "1"),
        ("Đầu then ngoài", "1"),
        ("Chữ thập đồng bộ", "2"),
        ("Chạc trục truyền CD", "2"),
        ("Nắp che bụi thân CD", "1")
    ]),
    ("7.3-CARDAN SAU", [
        ("Đầu then trong", "1"),
        ("Đầu then ngoài", "1"),
        ("Chữ thập đồng bộ", "2"),
        ("Chạc trục truyền CD", "2"),
        ("Nắp che bụi thân CD", "1")
    ]),
    ("8- CẦU TRƯỚC", [
        ("Vỏ cầu", "1b"),
        ("Vỏ khớp quay CH", "2"),
        ("Loa kèn đầu cầu", "2"),
        ("Bi trục đứng (27709)", "4"),
        ("Ba ngang (bàn tay ếch", "2"),
        ("Bộ vi sai", "1"),
        ("Bánh răng vành chậu", "1"),
        ("Bánh răng côn xoắn", "1"),
        ("Bán trục (láp ngang)", "2"),
        ("Đầu nối láp (Đ/sáp)", "1"),
        ("Vòng bi trục mayơ", "4"),
        ("Vòng bi", "1"),
        ("Vòng bi", "1"),
        ("Vòng bi", "1"),
        ("Mâyơ bánh xe", "2"),
        ("Gujông,Đ/ốc,móngT/kê", "12")
    ]),
    ("9- CẦU SAU", [
        ("Bộ vi sai", "1"),
        ("Bánh răng vành chậu", "1"),
        ("Bánh răng côn xoắn", "1"),
        ("Bán trục (láp ngang)", "2"),
        ("Đầu nối láp (Đ/sáp)", "1"),
        ("Vòng bi trục mayơ", "4"),
        ("May ơ bánh xe", "2")
    ]),
    ("10- HỆ THỐNG TREO", [
        ("Ống giảm xóc", "4"),
        ("Ắc + bạc nhíp trước", "2b"),
        ("Ắc + bạc nhíp sau", "2b"),
        ("Bát trượt nhíp trước", "2"),
        ("Bát trượt nhíp sau", "2"),
        ("U quang nhíp trước", "4"),
        ("U quang nhíp sau", "4"),
        ("Thanh giằng dọc sau", "2"),
        ("Thanh giằng ngang sau", "1"),
        ("Nhíp trước lá", "2b"),
        ("Nhíp sau lá", "2b")
    ]),
    ("11- THÙNG XE", [
        ("Sàn thùng", "1"),
        ("Thành đầu +Thành hông", "1+2"),
        ("Bửng hậu", "1"),
        ("Bộ gài bửng hậu", "2b"),
        ("Sắt chắn bùn+chống", "4b")
    ]),
    ("12- KHUNG XE", [
        ("Biển số", "2"),
        ("Cản trước", "1b"),
        ("Móc kéo trước", "1"),
        ("Đà dọc + ngang", "2+1"),
        ("Cản sau", "2"),
        ("Móc hậu", "1")
    ]),
    ("13- NỘI THẤT", [
        ("La phông", "1"),
        ("Tấm trải sàn (táp bi)", "1"),
        ("Che nắng", "3"),
        ("Bộ đệm ghế ngồi", "3b"),
        ("Khung ghế ngồi", "3b"),
        ("Bộ giảm xóc ghế", "2b")
    ]),
    ("14- HỆ THỐNG HƠI", [
        ("Bộ điều tiếu hơi", "1"),
        ("Bộ chia hơi phanh", "2"),
        ("Chia hơi 3 ngã", "1")
    ]),
    ("15- CA BIN", [
        ("Kính chắn gió", "2"),
        ("Kính sau cabin", "1"),
        ("Kính chiếu hậu", "2"),
        ("Tay kính chiếu hậu", "2"),
        ("Mặt nạ", "1b"),
        ("Ốp nhựa mui cabin", "1b"),
        ("Chữ KAMAZ + nhãn", "1b"),
        ("Nhíp cabin (5 lá)", "2b"),
        ("Ống giảm xóc cabin", "2"),
        ("Chống cabin", "1b"),
        ("Cơ cấu gài cabin", "1b"),
        ("Cửa hông", "2"),
        ("Tấm che cửa hông", "2"),
        ("Kính cửa hông", "2"),
        ("Kính lấy gió", "2"),
        ("Khóa gài kính gió", "2"),
        ("Ổ khóa cửa", "2"),
        ("Tay mở cửa trong", "2"),
        ("Tay mở cửa ngoài", "2"),
        ("Ổ quay kính", "2b"),
        ("Tay quay kính", "2"),
        ("Hộc tài liệu + nắp", "1b"),
        ("Ống lấygió hướng lên", "1b"),
        ("Bậc lên xuống", "1"),
        ("Bát lên bậc lên xuống", "2"),
        ("Tay nắm lên cabin", "2"),
        ("Giá bắt bình cứu hỏa", "1"),
        ("Dây tắt máy", "1"),
        ("Bầu lọc gió", "1"),
        ("Ruột lọc gió", "1"),
        ("Lọc nhiên liệu sơ cấp", "1"),
        ("Ruột lọc N/liệu SC", "1"),
        ("Thùng nhiên liệu", "1"),
        ("Nắp thùng nhiên liệu", "1"),
        ("Ống đổ thùng N/liệu", "1"),
        ("Phao N/liệu", "1b"),
        ("Giá thùng NL + đai", "1b"),
        ("Thùng dụng cụ", "1"),
        ("Thùng B/điện + nắp", "1b"),
        ("Giá bắt bầu hơi", "1b"),
        ("Đai bắt bầu hơi", "1b"),
        ("Bầu giảm thanh", "1"),
        ("Bộ ống bô xả + ống mềm", "1+2"),
        ("Giá lốp dự phòng", "1b"),
        ("Bánh xe dự phòng", "1b"),
        ("Vỏ ruột bánh xe", "6b"),
        ("Dây đai an toàn", "3b"),
        ("Két làm mát tuộc bô", "1"),
        ("Bầu nướ phụ", "1")
    ]),
    ("17- HỆ THỐNG LẠNH", [
        ("Máy nén", "1"),
        ("Két dàn nóng", "1"),
        ("Công tắc AC", "1"),
        ("Ống dàn lạnh", "4"),
        ("Ống thổi gió dàn lạnh", "5"),
        ("Rờ le", "2"),
        ("Van tiết lưu", "1"),
        ("Timer start", "1"),
        ("Quạt dàn nóng", "1"),
        ("Phin + lọc ga", "1b"),
        ("Kim vòi", "2"),
        ("Cảm biến gas", "1")
    ]),
    ("16- TRANG BỊ KHÁC", [
        ("Két nước", "1"),
        ("Nắp két nước", "1"),
        ("Két mát nhớt máy", "1")
    ])
]

output = {
    "templateVersion": 1,
    "vehicleCode": "KAMAZ-SELECT",
    "vehicleName": "Kamaz",
    "protocolType": "KIEM_CHON",
    "sections": []
}

total_items = 0
for sec_name, sec_items in items:
    section = {"name": sec_name, "items": []}
    for item_name, quantity in sec_items:
        clean_name = re.sub(r'^\s*-\s*', '', item_name)
        clean_name = re.sub(r'^\d+\s*\.?\s*', '', clean_name)
        section["items"].append({
            "name": clean_name,
            "quantity": quantity
        })
        total_items += 1
    output["sections"].append(section)

print(f"Total items extracted: {total_items}")

with open("src/templates/selections/KamazSelection.json", "w", encoding="utf-8") as f:
    json.dump(output, f, ensure_ascii=False, indent=2)

