import json
import re

items = [
    ("1.1. Trang bị đồng bộ", [
        ("Bộ điều khiển ga", "1b"),
        ("Cụm ống xả", "1"),
        ("Tấm che ống xả", "1"),
        ("Cụm ống hút", "1"),
        ("Nắp đậy BR cam cơ", "2"),
        ("Nắp đậy dàn cò mổ", "1"),
        ("Nắp đổ nhớt", "1"),
        ("Thước đo nhớt", "1"),
        ("Lọc nhớt", "1"),
        ("Cánh quạt", "1"),
        ("Bát bắt máy phát+tăngđưa", "1"),
        ("Puly trục cơ", "1"),
        ("Puly bơm nước", "1"),
        ("Khóa xả nước", "1"),
        ("Cạc te động cơ", "1"),
        ("Tấm dừng bánh đà", "1"),
        ("Chân máy", "2"),
        ("Thanh chống chân máy", "1"),
        ("Vòng găng", "4b"),
        ("Tay biên", "4"),
        ("Bạc thau tay biên", "4"),
        ("Xilanh", "4"),
        ("Thân máy", "1"),
        ("Đội căng xích", "1b"),
        ("Guốc căng xích", "2"),
        ("Bộ chế hòa khí 1H-2H", "1b"),
        ("Bộ Đ/khiển ga", "1b"),
        ("Ống + rắc co CHK", "1b"),
        ("Ống CHK, BCĐ", "1b"),
        ("Bơm xăng", "1b"),
        ("Cốc lọc xăng tinh", "1b"),
        ("Bộ chia điện tích hợp", "1b"),
        ("Nến điện", "4"),
        ("Dây phin", "4"),
        ("Chụp nến điện", "4")
    ]),
    ("1.2. Cụm – chi tiết", [
        ("Bơm nước", "1b"),
        ("Bơm nhớt", "1b"),
        ("Bộ ly hợp", "1b"),
        ("Đĩa ma sát ly hợp", "1"),
        ("Bánh đà + vành răng", "1b"),
        ("Nắp máy", "1b"),
        ("Xu páp xả + hút", "8"),
        ("Miệng xie XP xả + hút", "8"),
        ("Ống dẫn hướng XP", "8"),
        ("Lò xo xu páp + đế LX", "8b"),
        ("Chén chặn xu páp", "8"),
        ("Móng hãm xu páp", "16"),
        ("Con đội", "8"),
        ("Cảm biến tO nước", "1"),
        ("AS nhớt", "1"),
        ("Trục cam", "1b"),
        ("Xích kéo trục cam", "1"),
        ("Bánh xích cam - cơ", "1"),
        ("Trục cơ", "1"),
        ("Þ cổ chính", "1b"),
        ("Bạc cổ chính + biên", "2b"),
        ("Đệm dọc trục", "4"),
        ("Vòng bi trục cơ", "1"),
        ("Piston", "4"),
        ("Chốt piston", "4"),
        ("Phe gài chốt", "4")
    ]),
    ("2.2-HỆ THỐNG ĐIỆN", [
        ("Máy khởi động", "1"),
        ("Bạc thau + than KĐ", "2b"),
        ("Đầu nê khởi động", "1"),
        ("Bánh răng khởi động", "1"),
        ("Rờ le khởi động", "1"),
        ("Máy phát điện", "1b"),
        ("Puly máy phát", "1"),
        ("Bi MP", "2"),
        ("Than máy phát", "1b"),
        ("Vỉ tiết chế", "1"),
        ("Rờ le đề phụ", "1"),
        ("Bình điện 12v", "1"),
        ("Cọc bình điện", "2"),
        ("Cáp mát ( - )", "1"),
        ("Cáp lửa ( + )", "1"),
        ("Đồng hồ điện báo đèn", "1"),
        ("AS nhớt báo đèn", "1"),
        ("tO nước", "1"),
        ("nhiên liệu", "1"),
        ("tốc độ", "1"),
        ("Cụm báo tốc độ ( điện )", "1"),
        ("Cảm biến t0 nước", "1"),
        ("Cảm biến AS nhớt", "1"),
        ("Bóng đèn đồng hồ", "1b"),
        ("Tay gạt xi nhan + pha cốt", "1"),
        ("Tay gạt mưa + rửa kính", "1"),
        ("Công tắc điện", "1"),
        ("đèn trung tâm", "1"),
        ("đèn pha chính", "1"),
        ("Buton nhấn còi", "1"),
        ("Còi điện", "2"),
        ("Máy gạt mưa trước + sau", "1+1"),
        ("Bộ thanh chuyền", "1b"),
        ("Cần gạt mưa trước + sau", "2+1"),
        ("Chổi gạt mưa trước + sau", "2+1"),
        ("Bộ rửa kính", "1"),
        ("Bầu nước + đường ống", "1b"),
        ("Bơm + béc phun", "1+3"),
        ("Đèn pha", "2"),
        ("hiệu trước + đèn cản", "2+2"),
        ("hiệu sau", "2"),
        ("số de", "1"),
        ("soi biển số", "2"),
        ("khoang xe + lái", "2+1"),
        ("bậc cửa tài xế", "1"),
        ("bậc cửa hông", "1"),
        ("Cầu chì các loại", "1b"),
        ("Bộ dây điện", "1b"),
        ("Công tắc hành trình", "3"),
        ("Cục chớp", "1"),
        ("Cục Stop", "1"),
        ("Cục báo de", "1"),
        ("Cục báo phanh tay", "1"),
        ("Bộ lock cửa ( điện )", "1b")
    ]),
    ("3- HỆ THỐNG LÁI", [
        ("Chữ thập lái", "2"),
        ("Rô tuyn chuyển hướng", "2+2"),
        ("Rô tuyn trụ dưới", "2"),
        ("Thanh chuyển hướng", "2"),
        ("Cụm chữ A trên+rôtuyn", "2b"),
        ("Chữ A trên", "2b"),
        ("Bơm trợ lực lái", "1b"),
        ("Bost tay lái + thước lái", "1b"),
        ("Ống dầu lái", "2"),
        ("Cao su ruột gà bost lái", "2"),
        ("Thanh chữ a trên", "2b"),
        ("Thanh chữ a dưới", "2b"),
        ("Thanh ổn định ngang", "1"),
        ("Thanh ổn định dọc", "2"),
        ("Cao su chốn dập", "2")
    ]),
    ("4- HỆ THỐNG PHANH", [
        ("Bơm phanh cái", "1"),
        ("Lúp pê bơm phanh", "1"),
        ("Bầu chứa dầu phanh", "1"),
        ("Bầu trợ lực", "1"),
        ("Van hơi hút 1 chiều", "1"),
        ("Bơm phanh con sau", "2"),
        ("Bơm phanh con trước", "2"),
        ("Đĩa phanh trước", "2"),
        ("Tang trống phanh S", "2"),
        ("Guốc phanh T+S", "8"),
        ("Lò xo guốc phanh", "1b"),
        ("Tấm dừng bánh xe", "4"),
        ("Cụm chỉnh phanh", "2b"),
        ("Tay kéo phanh", "1"),
        ("Bộ dây cáp", "1b"),
        ("Điều hòa lực phanh", "1b")
    ]),
    ("5-DẪN ĐỘNG LY HỢP", [
        ("Bơm ly hợp chính", "1"),
        ("Bầu chứa dầu", "1"),
        ("Bơm ly hợp phụ", "1"),
        ("Bi tê - Ổ trượt bi tê", "1"),
        ("Ống dầu cao su ly hợp", "1"),
        ("Càng ngắt ly hợp", "1")
    ]),
    ("6- HỘP SỐ CHÍNH", [
        ("Cần số chính", "1"),
        ("Vỏ + nắp hộp số", "2"),
        ("Bộ đồng tốc 3/4", "1"),
        ("Bộ đồng tốc 4/5", "1"),
        ("Trục thứ cấp", "1"),
        ("B/răng 1, 2, 3 thứ cấp", "3"),
        ("Trục trung gian", "1"),
        ("B/răng 2, 3 trung gian", "2"),
        ("Bánh răng thường tiếp", "1"),
        ("Trục số de", "1"),
        ("Bánh răng số de", "1"),
        ("Bi rô lê", "1b"),
        ("V/bi trục SC", "1"),
        ("trục TC", "1"),
        ("trục TC", "1"),
        ("trục TG", "1"),
        ("Loa kèn", "1"),
        ("Trục sơ cấp", "1"),
        ("Bộ đồng tốc 1/2", "1"),
        ("trục TG", "1"),
        ("số de", "1"),
        ("Ổ bi kim BR1,2,3,5 TC", "4"),
        ("Bộ căn phe", "1b")
    ]),
    ("7- CARDAN", [
        ("Thân cardan liền", "1"),
        ("Mặt bích", "2"),
        ("Chữ thập đồng bộ", "2"),
        ("Đầu sáp láp dọc", "1")
    ]),
    ("8- DẦM CẦU TRƯỚC", [
        ("Vòng bi đùm ngoài", "1b"),
        ("đùm trong", "2"),
        ("Mâm bánh xe", "2"),
        ("May ơ bánh xe", "2"),
        ("Jujông tắc kê", "12"),
        ("Đai ốc tắc kê", "12")
    ]),
    ("9- CẦU SAU", [
        ("Bán trục (láp ngang)", "2"),
        ("Bộ vi sai", "1"),
        ("Bánh răng vành chậu", "1"),
        ("côn xoắn", "1"),
        ("Đầu nối cardan", "1"),
        ("Vòng bi vi sai", "2"),
        ("vi sai", "2"),
        ("đùm .trái", "1"),
        ("đùm ..phải", "1"),
        ("Mâm bánh xe", "2"),
        ("May ơ bánh xe", "2"),
        ("Jujông tắc kê", "12"),
        ("Đai ốc tắc kê", "12")
    ]),
    ("10- HỆ THỐNG TREO", [
        ("Ống giảm xóc trước", "2"),
        ("Ống giảm xóc sau", "2"),
        ("U quang nhíp sau", "4"),
        ("Nhíp sau lá", "2b"),
        ("Cao sau đầu nhíp simbock", "4b"),
        ("Cao su treo nhíp", "8")
    ]),
    ("11- KHUNG XE", [
        ("Biển số", "2"),
        ("Cản trước (nhựa)", "1b"),
        ("Bát móc kéo trước", "2"),
        ("Cản sau", "1"),
        ("Vòng móc kéo sau", "1")
    ]),
    ("12- NỘI THẤT", [
        ("La phông trần (nỉ)", "1b"),
        ("Bọc thành trong + cửa", "1b"),
        ("Tấm che nắng", "2"),
        ("Bộ đệm ghế", "08"),
        ("Khung ghế", "08"),
        ("Táp bi trải sàn + ván sàn", "1b")
    ]),
    ("13- TRANG BỊ ĐỒNG BỘ", [
        ("Két nước + nắp", "1b"),
        ("Cao su ống nước trên dưới", "2b"),
        ("Bọc gió két nước", "1"),
        ("Lọc gió", "1"),
        ("Cao su lọc gió", "1"),
        ("Ruột lọc gió", "1"),
        ("Thùng nhiên liệu", "1"),
        ("Nắp thùng nhiên liệu", "1"),
        ("Phao xăng", "1b"),
        ("Lọc nhiên liệu sơ cấp", "1"),
        ("Bô giảm thanh", "1"),
        ("Bộ ống xả", "1b"),
        ("Cao su chắn bùn T+ S", "4"),
        ("Giá lốp dự phòng", "1b"),
        ("Lốp dự phòng", "1b"),
        ("Lốp bánh xe", "4b")
    ]),
    ("14- CA BIN, THÂN XE", [
        ("Kính chắn gió", "1"),
        ("Kính chiếu hậu trong", "1"),
        ("Kính chiếu hậu ngoài", "2"),
        ("Tay kính chiếu hậu N", "2"),
        ("Mặt nạ", "1"),
        ("Ca bô", "1"),
        ("Khóa gài cabô", "1b"),
        ("Bệ táp lô nhựa cabin", "1b"),
        ("Cửa trước", "2"),
        ("Tấm che trong cửa", "2"),
        ("Cơ cấu khóa cửa", "2"),
        ("Tay mở cửa ngoài", "2"),
        ("Tay mở cửa trong", "2"),
        ("kính cửa hông", "2"),
        ("Cơ cấu quay kính", "2"),
        ("Tay quay kính", "2"),
        ("Cửa sau hông xe", "1b"),
        ("Tay mở ngoài cửa hông", "1"),
        ("Tay mở trongcửa hông", "1"),
        ("Tấm che koang xe +cửa", "5"),
        ("Tay nắm trong cửa", "1"),
        ("Khóa kính lùa", "4"),
        ("Ben hơi chống cửa sau", "2b"),
        ("Tay mở cửa ngoái", "1"),
        ("Tay mở cửa trong", "1"),
        ("Cao su giảm chấn cửa", "10"),
        ("Cao su chân máy", "2"),
        ("Cao su chân hộp số", "1"),
        ("Ang ten", "1"),
        ("Catsett", "1")
    ]),
    ("15- HỆ THỐNG LẠNH", [
        ("Máy nén", "1"),
        ("Két dàn nóng", "1"),
        ("Khung bảo vệ két DN", "1"),
        ("Ong dàn lạnh", "4"),
        ("Ong thổi gió dàn lạnh", "5"),
        ("Rờ le nhiệt", "2"),
        ("Van tiết lưu", "1"),
        ("Timer start", "1"),
        ("Kim vòi", "2"),
        ("Phin + lọc ga", "1b"),
        ("Dàn lạnh", "2"),
        ("Cảm biến ga", "1")
    ]),
    ("16- TRANG BỊ KHÁC", [
        ("Joang ống cánh cửa trước", "2"),
        ("Joang ống cửa hông", "1"),
        ("Joang ống cửa sau", "1"),
        ("Joang ống viền dưới cửa", "2"),
        ("Joang U cánh cửa", "2"),
        ("Joang ống viền ca bô", "2"),
        ("Joang U cánh cửa", "1"),
        ("Joang ống ca bô", "2"),
        ("Joang u quang kính", "2"),
        ("Joang kính cố định", "2"),
        ("Nẹp kính cửa trước", "2")
    ])
]

output = {
    "templateVersion": 1,
    "vehicleCode": "TOYOTAHIACE-SELECT",
    "vehicleName": "Toyota Hiace",
    "protocolType": "KIEM_CHON",
    "sections": []
}

total_items = 0
for sec_name, sec_items in items:
    section = {"name": sec_name, "items": []}
    for item_name, quantity in sec_items:
        clean_name = re.sub(r'^\s*-\s*', '', item_name)
        clean_name = re.sub(r'^\d+\s*\.?\s*', '', clean_name)
        section["items"].append({
            "name": clean_name,
            "quantity": quantity
        })
        total_items += 1
    output["sections"].append(section)

print(f"Total items extracted: {total_items}")

with open("src/templates/selections/ToyotaHiaceSelection.json", "w", encoding="utf-8") as f:
    json.dump(output, f, ensure_ascii=False, indent=2)

