import json
import re

items = [
    ("1.1. GIÁ BẮT ĐỘNG CƠ", [
        ("Cao su chân máy", "4"),
        ("Giá bắt phía trước động cơ", "1"),
        ("Bu lông chân máy", "4")
    ]),
    ("1.2. THÂN ĐỘNG CƠ", [
        ("Thân động cơ", "1"),
        ("Xy lanh", "4"),
        ("Đệm cao su xy lanh", "1"),
        ("Nắp đậy bánh răng cam", "1"),
        ("Đệm nắp đậy bánh răng cam", "1"),
        ("Nắp đậy đầu trục khuỷu", "1"),
        ("Mặt máy", "1"),
        ("Đệm nắp máy", "1b"),
        ("Nắp đậy dàn cò mổ", "2"),
        ("Đệm nắp đậy dàn cò mổ", "2"),
        ("Đệm đồng xi lanh", "1b"),
        ("Roăng làm đệm kim loại", "1b"),
        ("Dây đai các loại", "3"),
        ("Phớt đầu trục khuỷu", "1"),
        ("Phớt cuối trục khuỷu", "1")
    ]),
    ("1.3. TRỤC KHUỶU - BÁNH ĐÀ", [
        ("Bạc cổ chính", "5b"),
        ("Bạc cổ biên", "6b"),
        ("Đệm dọc trục", "4"),
        ("Trục cơ", "1"),
        ("Bạc áp trục khuỷu", "1/bộ"),
        ("Bánh đà toàn bộ", "1"),
        ("Vành răng bánh đà", "1"),
        ("Vòng chặn nhớt", "4"),
        ("Bích chặn trục khuỷu", "2")
    ]),
    ("1.4 PISTON-THANH TRUYỀN", [
        ("Piston", "8"),
        ("Chốt Piston", "8"),
        ("Phe gài chốt Piston", "16"),
        ("Vòng găng", "1/bộ"),
        ("Thanh truyền đồng bộ", "8"),
        ("Bạc thau thanh truyền", "8"),
        ("Bạc áp trục thanh truyền", "1/bộ"),
        ("Bu lông thanh truyền", "16"),
        ("Đai ốc thanh truyền", "16")
    ]),
    ("1.5 HỆ THỐNG PHỐI KHÍ", [
        ("Trục cam", "1"),
        ("Bạc trục cam", "4"),
        ("Bạc đầu nhỏ trục cam", "1"),
        ("Bánh răng trục cam", "1"),
        ("Xupap hút", "8"),
        ("Xupap xả", "8"),
        ("Ống dẫn hướng xupap hút", "8"),
        ("Ống dẫn hướng xupap xả", "8"),
        ("Đệm nắp cụm hút", "1b"),
        ("Móng hãm xupap", "32"),
        ("Đệm xoay dưới lò xo xupap hút", "8"),
        ("Đệm chặn trên lò xo xupap", "16"),
        ("Lò xo xupap", "16"),
        ("Trục cò mổ xupap", "2"),
        ("Cò mổ xupap", "16"),
        ("Đũa đẩy", "16"),
        ("Con đội", "16"),
        ("Su chụp xupap", "16"),
        ("Miệng xi e xupup hút", "8"),
        ("Đệm xoay dưới xupap xả", "8"),
        ("Miệng xi e xupup xả", "8"),
        ("Bulong điều chỉnh cò mổ", "16"),
        ("Lò xo cò mổ", "6"),
        ("Gối đỡ cò mổ", "8"),
        ("Bầu lọc gió đồng bộ", "1/cụm"),
        ("Gioăng làm kín", "1"),
        ("Lõi lọc gió", "1"),
        ("Nắp bầu lọc", "1"),
        ("Thân bầu lọc", "1"),
        ("Cụm xả", "2"),
        ("Vải lọc bầu Air", "1"),
        ("Ống su bầu Air", "1"),
        ("Cụm hút", "1"),
        ("Đệm ống xả", "3")
    ]),
    ("1.6 HỆ THỐNG LÀM MÁT", [
        ("Két nước", "1"),
        ("Bơm nước", "1b"),
        ("Khóa xả nước", "2"),
        ("Ống cao su két nước", "3"),
        ("Cao su chân két nước", "4"),
        ("Van hằng nhiệt", "2"),
        ("Khóa van sưởi ấm", "1"),
        ("Khóa van xả nước từ thân máy", "1"),
        ("Đường ống cấp nước", "1"),
        ("Đường ống thoát nước", "1"),
        ("Cổ ống bơm nước", "1"),
        ("Guồng bơm nước", "1"),
        ("Vòng bi trước puly tăng đai bơm nước", "1"),
        ("Vòng bi sau puly tăng đai bơm nước", "1"),
        ("Puly tăng đai bơm nước", "1"),
        ("Bích puly tăng đai bơm nước", "1"),
        ("Cánh quạt gió", "1"),
        ("Bích cánh quạt", "1")
    ]),
    ("1.7 HỆ THỐNG BÔI TRƠN", [
        ("Bơm dầu toàn bộ", "1b"),
        ("Thân bơm dầu", "1"),
        ("Nắp bơm dầu", "1"),
        ("Thước thăm dầu", "1"),
        ("Ống đổ dầu", "1"),
        ("Bầu lọc dầu thô", "1"),
        ("Phao dầu toàn bộ", "1/bộ"),
        ("Bánh răng bị động bơm dầu", "1"),
        ("Bánh răng chủ động dẫn động bơm dầu", "1"),
        ("Trục dẫn động bơm dầu", "1"),
        ("Ống dẻo dẫn dầu ra khỏi bầu lọc", "1"),
        ("Ống dẻo dẫn dầu vào bầu lọc", "1"),
        ("Ống dẫn hướng thước thăm dầu", "1"),
        ("Két dầu đồng bộ", "1"),
        ("Ông dẻo dẫn dầu", "2"),
        ("Khóa dầu đồng bộ", "1"),
        ("Đáy dầu toàn bộ", "1"),
        ("Đệm các te", "1")
    ]),
    ("1.8 HỆ THỐNG NHIÊN LIỆU", [
        ("Thùng nhiên liệu", "2"),
        ("Bơm xăng", "1b"),
        ("Bầu lọc xăng", "1b"),
        ("Chế hòa khí", "1b"),
        ("Ống hút", "1"),
        ("Bầu lọc lưới", "1"),
        ("Nắp thùng nhiên liệu", "1"),
        ("Bầu lọc lắng", "1"),
        ("Khóa van xăng", "1"),
        ("Ty ô nhiên liệu", "1b"),
        ("Ty ô cao su", "1b"),
        ("Hộp van của thùng", "1"),
        ("Bàn đạp ga", "1"),
        ("Dây kéo gió toàn bộ", "1b"),
        ("Dây kéo tay ga toàn bộ", "1b"),
        ("Bộ hạn chế vòng quay", "1b"),
        ("Bầu lọc không khí", "1b")
    ]),
    ("1.9 LY HỢP VÀ DẪN ĐỘNG LY HỢP", [
        ("Vòng tỳ ly hợp", "1"),
        ("Bàn ép ly hợp", "1"),
        ("Đĩa ma sát", "1"),
        ("Bi tê 131", "1b"),
        ("Vòi bơm mỡ bi ngắt ly hợp", "1"),
        ("Bi kim cần bẩy ly hợp", "3"),
        ("Cần bẩy ly hợp", "4"),
        ("Nạng tách ly hợp", "1"),
        ("Càng ngắt ly hợp", "1"),
        ("Bàn đạp ly hợp", "1"),
        ("Bộ đẫn động ly hợp", "1b"),
        ("Ổ trượt bi tê", "1"),
        ("Vòng bi 6006.Z", "2"),
        ("Vòng bi 6201-2RS", "2"),
        ("Vòng bi 6207", "2"),
        ("Lò xo chân ga + côn", "1")
    ]),
    ("2.1 HỘP SỐ", [
        ("Hộp số đồng bộ", "1b"),
        ("Trục sơ cấp", "1"),
        ("Nắp đậy ổ bi trục sơ cấp", "1"),
        ("Trục thứ cấp", "1"),
        ("Bộ đồng tốc 4 – 5", "1"),
        ("Bộ đồng tốc 2 – 3", "1"),
        ("Trục trung gian", "1"),
        ("Bánh răng 2 TG", "1"),
        ("Bánh răng 3 TG", "1"),
        ("Bánh răng 5 TG", "1"),
        ("Bánh răng số lùi", "1"),
        ("Trục số lùi", "1"),
        ("Bi trục SC 50217", "2"),
        ("Bi trục TC 50411", "2"),
        ("Đầu nối láp", "1"),
        ("Nút nạp, xả dầu K1/2", "2"),
        ("Trục trượt gài số 1 và số 2", "1"),
        ("Trục trượt gài số 3 và 4", "1"),
        ("Trục trượt gài số lùi", "1"),
        ("Nấp hộp số", "1"),
        ("Nạng gài số 1 và số 2", "1"),
        ("Nạng gài số 3 và số 4", "1"),
        ("Nạng gài số lùi", "1"),
        ("Cần gài số", "1"),
        ("Ổ đỡ cần đi số", "1"),
        ("Cao su che bụi cần đi số", "1"),
        ("Lò xo cần đi số", "1"),
        ("Bánh vít báo tốc độ", "1"),
        ("Trục vít báo tốc độ", "1"),
        ("Thanh điều khiển đi số", "1"),
        ("Cần cơ cấu đi số", "1"),
        ("Cao su che bụi cần cơ cấu đi số", "1"),
        ("Lò xo cần cơ cầu đi số", "1"),
        ("Đầu nối thanh đi số", "1"),
        ("Bánh răng trung gian", "1"),
        ("Bánh răng số 4", "1"),
        ("Trục số lùi", "1"),
        ("Vòng bi kim trục số lùi", "1"),
        ("Ống dẫn hướng trục vít báo tốc độ", "1"),
        ("Ổ đỡ bi trục thứ cấp", "1"),
        ("Phớt hộp số", "4"),
        ("Cao su chân hộp số phụ", "4")
    ]),
    ("2.2.TRỤC TRUYỀN", [
        ("Trục truyền toàn bộ", "1"),
        ("Trục truyền cầu sau toàn bộ", "1"),
        ("Trục truyền trung gian đoạn trước", "1"),
        ("Trục truyền trung gian đoạn sau", "1"),
        ("Đầu then trong", "2"),
        ("Chữ thập đồng bộ", "4"),
        ("Đầu then ngoài", "2"),
        ("Mặt bích nối cardan", "2"),
        ("Nắp che bụi thân cardan", "1"),
        ("Nắp vặn cardan", "1"),
        ("Bi các đăng", "4"),
        ("Xẹc lip các đăng", "16")
    ]),
    ("2.3. CẦU TRƯỚC", [
        ("Vỏ cầu", "1"),
        ("Nút thông hơi", "1"),
        ("Nút xả dầu K1/2", "1"),
        ("Nút chặn bi cụm vi sai", "2"),
        ("Nút đổ dầu", "1"),
        ("Vi sai toàn bộ", "1b"),
        ("Nắp cổ sáp", "1b"),
        ("Thân lắp bi cổ sáp", "1"),
        ("Gối đỡ cụm vi sai bên phải", "1"),
        ("Gối đỡ cụm vi sai bên trái", "1"),
        ("Bộ bánh răng vành chậu", "1"),
        ("Ổ bi sau trục bánh răng quả dứa", "1"),
        ("Ổ bi trước trục bánh răng quả dứa", "1"),
        ("Phớt cầu", "1"),
        ("Bánh răng côn xoắn", "1"),
        ("Bán trục", "4"),
        ("Bánh răng bán trục", "4"),
        ("Bánh răng vệ tinh cụm vi sai", "1"),
        ("Trục chữa thập cụm vi sai", "1"),
        ("Phớt trục gài cầu", "10"),
        ("Phớt + nỉ đầu ông sư", "2bộ")
    ]),
    ("2.4. CẦU GIỮA", [
        ("Vỏ cầu", "1"),
        ("Nút thông hơi", "1"),
        ("Nút xả dầu K1/2", "1"),
        ("Nút chặn bi cụm vi sai", "2"),
        ("Nút đổ dầu", "1"),
        ("Vi sai toàn bộ", "1"),
        ("Nắp cổ sáp", "1"),
        ("Thân lắp bi cổ sáp", "1"),
        ("Gối đỡ cụm vi sai bên phải", "1"),
        ("Gối đỡ cụm vi sai bên trái", "1"),
        ("Bộ bánh răng vành chậu", "1 bộ"),
        ("Ổ bi cụm vi sai", "2"),
        ("Ổ bi sau trục bánh răng quả dứa", "2"),
        ("Ổ bi trước trục bánh răng quả dứa", "1"),
        ("Phớt cầu", "2"),
        ("Bánh răng côn xoắn", "1"),
        ("Bán trục", "2"),
        ("Bánh răng bán trục", "2"),
        ("Bánh răng vệ tinh cụm vi sai", "4"),
        ("Trục chữa thập cụm vi sai", "1"),
        ("Phớt trục gài cầu", "2")
    ]),
    ("2.5. CẦU SAU", [
        ("Vỏ cầu", "1"),
        ("Nút thông hơi", "1"),
        ("Nút xả dầu K1/2", "1"),
        ("Nút chặn bi cụm vi sai", "2"),
        ("Nút đổ dầu", "1"),
        ("Vi sai toàn bộ", "1b"),
        ("Nắp cổ sáp", "1"),
        ("Thân lắp bi cổ sáp", "1"),
        ("Gối đỡ cụm vi sai bên phải", "1"),
        ("Gối đỡ cụm vi sai bên trái", "1"),
        ("Bộ bánh răng vành chậu", "1"),
        ("Ổ bi sau trục bánh răng quả dứa", "2"),
        ("Ổ bi trước trục bánh răng quả dứa", "1"),
        ("Phớt cầu", "2"),
        ("Bánh răng côn xoắn", "1"),
        ("Bán trục", "2"),
        ("Bánh răng bán trục", "2"),
        ("Bánh răng vệ tinh cụm vi sai", "4"),
        ("Trục chữa thập cụm vi sai", "1"),
        ("Phớt trục gài cầu", "2")
    ]),
    ("2.6. BÁNH XE VÀ MOAY Ơ", [
        ("Vành bánh xe", "5"),
        ("Moay ơ bánh trước", "2"),
        ("Ổ bi moay ơ trước phía trong", "2"),
        ("Ổ bi moay ơ trước phía ngoài", "2"),
        ("Phớt chắn mỡ moay ơ trước", "2"),
        ("Phớt chắn mỡ moay ơ giữa", "2"),
        ("Phớt chắn mỡ moay ơ sau", "2"),
        ("Vòng bi trong moay ơ sau", "2"),
        ("Vòng bi ngoài moay ơ sau", "2"),
        ("Moay ơ bánh sau", "2"),
        ("La giăng", "2"),
        ("Vành chặn lốp", "14"),
        ("Vành khóa lốp", "7"),
        ("Chột tickê + êru bánh xe", "48bộ"),
        ("Săm, yếm,Lốp xe 12.00-20", "7"),
        ("Giá lốp dự phòng toàn bộ", "1 bộ"),
        ("Trục bánh răng", "1"),
        ("Bạc trục", "2"),
        ("Cá hãm", "1"),
        ("Dây cáp", "2"),
        ("Cáp tời", "50"),
        ("Hộp tời đồng bộ", "1")
    ]),
    ("2.7. HỆ THỐNG TREO", [
        ("Nhíp trước toàn bộ (17 lá)", "2 bộ"),
        ("Cao su ốp nhíp", "2"),
        ("Quang nhíp trước", "4"),
        ("Đai ốc quang nhíp", "8"),
        ("Đệm tỳ đầu nhíp trước", "2"),
        ("Ốp mõ nhíp trước", "2"),
        ("Ốp mõ nhíp sau", "2"),
        ("Cao su tỳ nhíp", "2"),
        ("Ốp cao su tỳ nhíp", "2"),
        ("Cao su mõ nhíp phía trên", "4"),
        ("Cao su mõ nhíp phía dưới", "4"),
        ("Ốp nhíp", "2"),
        ("Giảm sóc ống thủy lực đồng bộ", "4"),
        ("Cao su giảm xóc", "16"),
        ("Trục lắp giảm xóc", "8"),
        ("Nhíp sau toàn bộ (17 lá)", "2 bộ"),
        ("Cao su mõ nhíp phía trên", "4"),
        ("Cao su mõ nhíp phía dưới", "4"),
        ("Ốp nhíp", "2"),
        ("Ốp mõ nhíp trước", "2"),
        ("Ốp mõ nhíp sau", "2"),
        ("Đệm tỳ đầu nhíp trước", "2"),
        ("Trục cân bằng", "2"),
        ("Bạc trục cân bằng", "2"),
        ("Thân thanh giằng cầu", "6"),
        ("Quả táo thanh giằng cầu", "12"),
        ("Bạc quả táo thanh giằng cầu", "12"),
        ("U quang nhíp", "8"),
        ("Bát nhíp trước + sau", "8")
    ]),
    ("2.8. HỆ THỐNG LÁI", [
        ("Hộp tay lái toàn bộ", "1"),
        ("Siêu + Phớt hộp tay lái", "1b"),
        ("Vỏ hộp tay lái", "1"),
        ("Trục rẽ quạt", "1"),
        ("Trục hộp lái", "1"),
        ("Con lăn", "1"),
        ("Đòn quay lái", "1"),
        ("Phớt chắn dầu trục rẽ quạt", "1"),
        ("Vòng bi trục rẽ quạt", "1"),
        ("Bạc trục rẽ quạt", "1"),
        ("Bi ống tay lái", "2"),
        ("Các đăng lái", "2"),
        ("Bi các đăng lái", "2"),
        ("Ca vét các đăng lái", "2"),
        ("Vành tay lái", "1"),
        ("Ống tay lái", "1"),
        ("Trục truyền lái", "1"),
        ("Trục tay lái", "1"),
        ("Thanh chuyển hướng ngang", "1"),
        ("Rotuyn giằng cầu", "8"),
        ("Rotuyl chuyển hướng", "4"),
        ("Xi lanh trợ lực lái", "1b"),
        ("Xi lanh trợ lực lái toàn bộ", "1/cụm"),
        ("Thân xy lanh", "1"),
        ("Piston", "1"),
        ("Thanh đẩy", "1"),
        ("Đầu nối", "1"),
        ("Rô tuyn xy lanh trợ lực", "1"),
        ("Cao su che bụi rô tuyn", "1"),
        ("Giá lắp xy lanh", "1"),
        ("Chốt xy lanh trợ lực", "1"),
        ("Bơm trợ lực lái", "1b"),
        ("Bơm trợ lực lái đồng bộ", "1"),
        ("Puly bơm trợ lực", "1"),
        ("Trục bơm trợ lực", "1"),
        ("Rô to", "1"),
        ("Stato", "1"),
        ("Cánh bơm", "1bộ"),
        ("Vòng bi", "2"),
        ("Phớt làm kín", "1"),
        ("Nắp bơm", "1"),
        ("Thân bơm", "1"),
        ("Đế bơm", "1"),
        ("Bầu đựng dầu", "1"),
        ("Lọc dầu", "1"),
        ("Nắp bầu đựng dầu", "1"),
        ("Đế bầu đựng dầu", "1"),
        ("Lò xo van điều áp", "1"),
        ("Van điều áp", "1"),
        ("Ống dẻo từ van phân phối đến xy lanh trợ lực", "2"),
        ("Ống dẻo từ bơm trợ lực đến van phân phối", "1"),
        ("Đường ống hồi từ van phân phối về bơm", "1")
    ]),
    ("2.8. HỆ THỐNG PHANH", [
        ("Mâm phanh trước", "2"),
        ("Tang trống phanh", "2"),
        ("Trục cam phanh", "2"),
        ("Bu lông lệch tâm", "4"),
        ("Đệm bu lông lệch tâm", "2"),
        ("Bạc lệch tâm", "4"),
        ("Giá đỡ trục cam phanh trước", "2"),
        ("Lò xo hồi vị guốc phanh", "2"),
        ("Con lăn guốc phanh", "4"),
        ("Bạc trục cam phanh", "4"),
        ("Guốc phanh", "4"),
        ("Má phanh", "8"),
        ("Mâm phanh", "2"),
        ("Tang trống phanh", "2"),
        ("Trục cam phanh", "2"),
        ("Bu lông lệch tâm", "4"),
        ("Đệm bu lông lệch tâm", "2"),
        ("Bạc lệch tâm", "4"),
        ("GIá đỡ trục cam phanh", "2"),
        ("Lò xo hồi vị guốc phanh", "2"),
        ("Con lăn guốc phanh", "4"),
        ("Bạc trục cam phanh", "4"),
        ("Guốc phanh", "4"),
        ("Má phanh", "8"),
        ("Guốc phanh", "4"),
        ("Má phanh", "8"),
        ("Xương phanh", "4"),
        ("Bu lông lệch tâm", "4"),
        ("Đệm bu lông lệch tâm", "2"),
        ("Bạc lệch tâm", "4"),
        ("Lò xo hồi vị guốc phanh", "2"),
        ("Con lăn guốc phanh", "4"),
        ("Tang trống phanh sau", "2"),
        ("Trục cam phanh sau", "2"),
        ("Mâm phanh sau", "2"),
        ("Giá đỡ trục cam phanh sau", "2"),
        ("Bàn đạp phanh", "1"),
        ("Cần bàn đạp phanh", "1"),
        ("Tyo phanh cao su", "6"),
        ("Vải má phanh chân", "1b"),
        ("Bạc trục bàn đạp", "2"),
        ("Ty nối", "1"),
        ("Cụm chỉnh phanh", "1b"),
        ("Lò xo hồi vị bàn đạp phanh", "1"),
        ("Cum chỉnh phanh", "1"),
        ("Tang trống phanh tay", "1"),
        ("Cần kéo phanh tay", "1"),
        ("Guốc phanh tay +lò xo", "2"),
        ("Vải má phanh tay", "2"),
        ("Tổng phanh toàn bộ", "1b"),
        ("Máy nén khí đồng bộ", "1b"),
        ("Ống nhớt+rắc co bình hơi", "1b"),
        ("Bình chứa khí toàn bộ", "2"),
        ("Van xả", "2"),
        ("Van điều tiết áp suất bình hơi", "1"),
        ("Van bảo vệ bốn ngã", "1"),
        ("Van an toàn", "1"),
        ("Bộ điều chỉnh áp suất", "1"),
        ("Cụm điều hòa lực phanh", "1"),
        ("Bình ngưng khí", "1"),
        ("Bầu phanh trước toàn bộ", "2"),
        ("Nắp bầu phanh", "2"),
        ("Kẹp bầu phanh", "4"),
        ("Màng da phanh hơi", "6"),
        ("Ty bầu phanh", "2"),
        ("Lò xo bầu phanh", "2"),
        ("Bích thân bầu phanh", "2"),
        ("Thân bầu phanh", "2"),
        ("Cao su che bụi", "2"),
        ("Bầu phanh sau toàn bộ", "4"),
        ("Thân bầu phanh", "2"),
        ("Kẹp bầu phanh", "4"),
        ("Bích thân bầu phanh", "2"),
        ("Lò xo bầu phanh", "2"),
        ("Ty bầu phanh", "2"),
        ("Cao su bầu phanh", "2"),
        ("Cao su che bụi", "2"),
        ("Nắp bầu phanh", "2"),
        ("Piston bầu tích năng", "2"),
        ("Trục bầu tích năng", "2"),
        ("Lò xo bầu tích năng", "2"),
        ("Xy lanh bầu tích năng", "2"),
        ("Bu lông điều chỉnh", "2")
    ]),
    ("3.1. ĐIỆN ĐỘNG CƠ", [
        ("Máy phát điện đồng bộ", "1b"),
        ("Stato", "1"),
        ("Roto máy phát", "1"),
        ("Puly máy phát", "1"),
        ("Chổi than phải", "1"),
        ("Chổi than trái", "1"),
        ("Vòng bi trước", "1"),
        ("Vòng bi sau", "1"),
        ("Tiết chế toàn bộ", "1"),
        ("Cánh quạt máy phát", "1"),
        ("Cần tăng đai máy phát", "1"),
        ("Vỏ máy phát", "1"),
        ("Nắp máy phát", "1"),
        ("Bộ chia điện", "1b"),
        ("Tăng điện", "1"),
        ("Bugi", "8"),
        ("Dây cao áp", "1/bộ"),
        ("Sứ chụp dây cao áp", "8"),
        ("Đầu kẹp dây cao áp", "18"),
        ("Hộp đánh lửa", "1"),
        ("Điện trở phụ", "1"),
        ("Bạc đỡ", "1"),
        ("Máy khởi động toàn bộ", "1b"),
        ("Cụm rơ le máy khởi động", "1/cụm"),
        ("Rơ le trung gian", "1/cụm"),
        ("Stato", "1/cụm"),
        ("Ro to", "1/cụm"),
        ("Cụm bánh răng khởi động", "1/cụm"),
        ("Chổi than", "4"),
        ("Bạc", "1")
    ]),
    ("3.2. ĐIỆN THÂN XE", [
        ("Hộp điện trở 2 cọc", "1"),
        ("Cầu chì", "1b"),
        ("Cọc bình điện", "2"),
        ("Đảo pha cốt chân", "1"),
        ("Đèn pha cốt", "2b"),
        ("Đèn hậu", "2"),
        ("Đèn trần", "1"),
        ("Đèn soi biển số", "1"),
        ("Đèn soi máy", "1"),
        ("Đèn hiệu trước", "2"),
        ("Đèn hiệu sau", "2"),
        ("Bóng đèn taplo", "10"),
        ("Đuôi đèn đồng hồ", "10"),
        ("Khóa điện", "1"),
        ("Còi điện", "1"),
        ("Cáp lửa+mát", "6m"),
        ("Đồng hồ hơi", "1"),
        ("Đồng hồ nhiệt độ nước", "1"),
        ("Đồng hồ báo điện", "1"),
        ("Đồng hồ báo áp suất dầu", "1"),
        ("Đồng hồ báo nhiên liệu", "1"),
        ("Đèn chiếu sáng bảng đ. hồ", "7"),
        ("Bóng đèn con", "6"),
        ("Đồng hồ báo tốc độ", "1"),
        ("Bộ công tắc đèn trong xe", "1/bộ"),
        ("Dây Km", "1"),
        ("Cảm biến báo mức N. liệu", "1"),
        ("Cảm biến báo n. độ nước", "1"),
        ("Cảm biến báo áp suất dầu", "1"),
        ("Rơ le gài cầu trước", "1"),
        ("Dây điện toàn bộ", "1/bộ"),
        ("Công tắc xin đường", "1"),
        ("Công tắc nhỏ 1, 2 nấc", "2"),
        ("Đèn xin đường trước", "2"),
        ("Công tắc cắt mát", "1"),
        ("Đèn báo kích thước", "2"),
        ("Cục chớp", "1"),
        ("Bộ rung phòng hỏng", "1"),
        ("Bình điện", "1")
    ]),
    ("4. KHUNG XE", [
        ("Khung xe toàn bộ", "1"),
        ("Móc kéo hậu toàn bộ", "1"),
        ("Chắn đòn", "1"),
        ("Móc kéo trước", "2"),
        ("Mõ nhíp trước phía trước", "2"),
        ("Mõ nhíp trước phía sau", "2"),
        ("Giá đỡ nhíp phụ", "4"),
        ("Mõ nhíp sau phía trước", "2"),
        ("Mõ nhíp sau phía sau", "2"),
        ("Giá bắt đầu trên giảm xóc", "2")
    ]),
    ("5.THÂN XE BUỒNG LÁI", [
        ("Máy gạt mưa", "1"),
        ("Gọng + Chổi gạt mưa", "2b"),
        ("Cần gạt mưa bên phải", "1"),
        ("Cần gạt mưa bên trái", "1"),
        ("Thanh truyền gạt mưa", "1b"),
        ("Khóa gạt mưa hơi", "1"),
        ("Khung xương + tấm bọc buồng lái", "1"),
        ("Cánh cửa buồng lái trái - phải toàn bộ", "2"),
        ("Kính chắn gió", "1"),
        ("Kính chiếu hậu", "2"),
        ("Khoá cửa trái -phải toàn bộ", "2"),
        ("Kính hậu buồng lái", "1"),
        ("Kính cửa trái- phải", "2"),
        ("Kính chéo trái - phải", "2"),
        ("Tay khoá kính chéo trái-phải", "2"),
        ("Cơ cấu nâng kính trái-phải", "2"),
        ("Tay quay nâng kính", "2"),
        ("Tay mở cửa trong", "2"),
        ("Tay mở cửa ngoài", "2"),
        ("Cửa gió nóc buồng lái", "2"),
        ("Cụm tay mở cửa gió nóc buồng lái", "2"),
        ("Bản lề nâng ca pô trái phải", "2"),
        ("Ca pô", "1"),
        ("Khoá ca pô toàn bộ", "1"),
        ("Ca lăng", "1"),
        ("Tai xe trái + phải", "2"),
        ("Gương + giá gương toàn bộ", "2"),
        ("Đệm làm kín cánh cửa", "2"),
        ("Đệm kính cửa gió", "2"),
        ("Cùm ống xả", "3"),
        ("Gioăng kính chắn gió", "1"),
        ("Chèn gioăng kính chắn gió", "1"),
        ("Roăng chữ L", "1"),
        ("Roăng xốp", "1"),
        ("Chèn gioăng kính hậu", "1"),
        ("Cao su đệm chân buồng lái", "2"),
        ("Su chắn bùn", "2"),
        ("Bậc lên xuống trái + phải", "2"),
        ("Trải sàn", "1"),
        ("Vải chụp cần số", "2")
    ]),
    ("ĐỆM GHẾ", [
        ("Khung ghế lái", "1"),
        ("Đệm ngồi lái", "1"),
        ("Đệm tựa lái", "1"),
        ("Khung ghế phụ", "1"),
        ("Đệm ngồi bên phụ", "1"),
        ("Đệm tựa bên phụ", "1")
    ]),
    ("6. ĐIỆN THÙNG XE", [
        ("Đèn trần", "4"),
        ("Đèn chiếu sáng phòng không", "1"),
        ("Đèn cổ cò", "2"),
        ("Ổ cắm điện 1 pha", "4"),
        ("Đồng hồ ampe", "3"),
        ("Công tắc kích từ", "1"),
        ("Đèn soi bảng điều khiển", "1"),
        ("Đồng hồ Vôn", "1"),
        ("Đồng hồ tần số", "1"),
        ("Đồng hồ Ôm", "1"),
        ("Hộp đóng, ngắt nguồn", "1"),
        ("Công tắc 3 pha", "1"),
        ("Công tắc đảo mạch", "1"),
        ("Cầu nối", "6"),
        ("Công tắc điện", "6"),
        ("Ổ cắm 220v", "4"),
        ("Phít cắm", "6"),
        ("Cầu chì ống", "8")
    ])
]

output = {
    "templateVersion": 1,
    "vehicleCode": "ZIL131-SELECT",
    "vehicleName": "ZIL 131",
    "protocolType": "KIEM_CHON",
    "sections": []
}

total_items = 0
for sec_name, sec_items in items:
    section = {"name": sec_name, "items": []}
    for item_name, quantity in sec_items:
        clean_name = re.sub(r'^\s*-\s*', '', item_name)
        clean_name = re.sub(r'^\d+\s*\.?\s*', '', clean_name)
        section["items"].append({
            "name": clean_name,
            "quantity": quantity
        })
        total_items += 1
    output["sections"].append(section)

print(f"Total items extracted: {total_items}")

with open("src/templates/selections/Zil131Selection.json", "w", encoding="utf-8") as f:
    json.dump(output, f, ensure_ascii=False, indent=2)

