import json
import re

items = [
    ("1.1- Trang bị đồng bộ", [
        ("Bộ điều khiển ga", "1b"),
        ("Cụm ống xả", "1"),
        ("Tấm che ống xả", "1"),
        ("Cụm ống hút", "1"),
        ("Nắp đậy BR cam cơ", "1b"),
        ("Nắp đậy dàn cò mổ", "1"),
        ("Nắp đổ nhớt", "1"),
        ("Thước đo nhớt", "1"),
        ("Lọc nhớt", "1"),
        ("Lọc nhiên liệu tinh", "1"),
        ("Bơm tay", "1"),
        ("Cánh quạt", "1"),
        ("Bát bắt máy phát+tăngđưa", "1"),
        ("Puly trục cơ 3R", "1"),
        ("Puly bơm nước 2R", "1"),
        ("Van hằng nhiệt", "1"),
        ("Cạc te động cơ", "1"),
        ("Tấm dừng bánh đà", "1"),
        ("Chân máy", "2"),
        ("Dây đai", "1b")
    ]),
    ("1.2- Cụm – chi tiết", [
        ("Bơm nước", "1b"),
        ("Bơm nhớt", "1b"),
        ("Bộ ly hợp", "1b"),
        ("Đĩa ma sát ly hợp", "1"),
        ("Bánh đà + vành răng", "1b"),
        ("Tuôc bô tăng áp", "1b"),
        ("Nắp máy", "1b"),
        ("Xu páp xả + hút", "8"),
        ("Miệng xie XP xả + hút", "8"),
        ("Ống dẫn hướng XP", "8"),
        ("Lò xo xu páp + đế LX", "8b"),
        ("Chén chặn xu páp", "8"),
        ("Móng hãm xu páp", "16"),
        ("Trục cam", "1"),
        ("Bánh răng trung gian+bạc", "2+2"),
        ("Bánh răng cam - cơ", "1b"),
        ("Trục cơ", "1"),
        ("Bạc cổ chính + biên", "2b"),
        ("Đệm dọc trục", "4"),
        ("Vòng bi trục cơ", "1"),
        ("Piston", "4"),
        ("Chốt piston", "4"),
        ("Phe gài chốt", "8"),
        ("Vòng găng", "4b"),
        ("Tay biên", "4"),
        ("Bạc thau tay biên", "4"),
        ("Xilanh", "4"),
        ("Thân máy", "1"),
        ("Cảm biến lưu lượng khí nạp", "1"),
        ("Kim phun", "4"),
        ("Bơm cao áp", "1b"),
        ("Đường ống cao áp", "4b"),
        ("Đường ống nhiên liệu", "1b"),
        ("Trục cân bằng + bạc", "2+6"),
        ("Đế lỗ lắp kim phun", "4"),
        ("Cụm bi tăng đưa", "2")
    ]),
    ("2- HỆ THỐNG ĐIỆN", [
        ("Máy khởi động", "1"),
        ("Bạc thau + than KĐ", "2b"),
        ("Đầu nê khởi động", "1"),
        ("Bánh răng khởi động", "1"),
        ("Rờ le khởi động", "1"),
        ("Máy phát điện", "1b"),
        ("Puly máy phát", "1"),
        ("Bi MP", "2"),
        ("Than máy phát", "1b"),
        ("Vỉ tiết chế", "1"),
        ("Rờ le đề phụ", "1"),
        ("Bình điện 12v", "1"),
        ("Cọc bình điện", "2"),
        ("Cáp mát ( - )", "1"),
        ("Cáp lửa ( + )", "1"),
        ("Đồng hồ điện báo đèn", "1"),
        ("AS nhớt báo đèn", "1"),
        ("tO nước", "1"),
        ("nhiên liệu", "1"),
        ("tốc độ", "1"),
        ("Cụm tốc độ + dây", "1"),
        ("Bóng đèn đồng hồ", "1b"),
        ("Công tắc điện", "1"),
        ("gạt mưa+rửa kính", "1+1"),
        ("trungtâm+pha,xynhan", "1b"),
        ("Buton nhấn còi", "1"),
        ("Còi điện", "2"),
        ("Máy gạt mưa trước + sau", "2b"),
        ("Bộ thanh chuyền", "1b"),
        ("Cần gạt mưa", "2"),
        ("Chổi gạt mưa", "2"),
        ("Cần gạt mưa sau", "1"),
        ("Chổi gạt mưa sau", "1"),
        ("Bộ rửa kính T + S", "1+1"),
        ("Bầu nước + môtơ", "1+1"),
        ("Ống + béc phun", "1b"),
        ("Đèn pha", "2"),
        ("hiệu trước cụm", "2"),
        ("hiệu sau cụm", "2"),
        ("biển số", "2"),
        ("khoang xe", "2"),
        ("dừng bổ sung", "1"),
        ("cửa cốp sau", "1"),
        ("Cầu chì các loại", "1b"),
        ("Rờ le các loại", "1b"),
        ("Bộ dây điện", "1b"),
        ("Công tắc ưu tiên", "1"),
        ("Cục Stop + Cục chớp", "1+1"),
        ("Cục báo de", "1"),
        ("Cục báo phanh tay", "1"),
        ("Cảm biến tO nước", "1"),
        ("AS nhớt", "1")
    ]),
    ("3- HỆ THỐNG LÁI", [
        ("Vành tay lái", "1"),
        ("Chữ thập lái", "2"),
        ("Rô tuyn chuyển hướng", "2+2"),
        ("Rô tuyn trụ", "2"),
        ("Thanh chuyển hướng", "2"),
        ("Cụm chữ A trên+rôtuyn", "2b"),
        ("Bơm trợ lực lái", "1b"),
        ("Bost tay lái + thước lái", "1b"),
        ("Cao su bost lái", "2"),
        ("Cao su ruột gà bost lái", "2")
    ]),
    ("4- HỆ THỐNG PHANH", [
        ("Bơm phanh cái", "1"),
        ("Lúp pê bơm phanh", "1"),
        ("Bầu chứa dầu phanh", "1"),
        ("Bầu trợ lực", "1"),
        ("Van hơi hút 1 chiều", "1"),
        ("Bơm phanh con sau", "2"),
        ("Bơm phanh con trước", "2"),
        ("Đĩa phanh trước", "2"),
        ("Tang chống sau", "2"),
        ("Guốc phanh", "8"),
        ("Lò xo guốc phanh", "1b"),
        ("Tấm dừng bánh xe", "4"),
        ("Đường ống phanh", "1b"),
        ("Cụm chỉnh phanh", "2b"),
        ("Tay kéo phanh", "1"),
        ("Bộ dây cáp", "1b")
    ]),
    ("5-DẪN ĐỘNG LY HỢP", [
        ("Bơm ly hợp chính", "1"),
        ("Bầu chứa dầu", "1"),
        ("Bơm ly hợp phụ", "1"),
        ("Bi tê", "1"),
        ("Ổ trượt bi tê", "1"),
        ("Càng ngắt ly hợp", "1")
    ]),
    ("6- HỘP SỐ", [
        ("Cần số chính", "1"),
        ("Vỏ + nắp hộp số", "2"),
        ("Bộ đồng tốc 3/4", "1"),
        ("Bộ đồng tốc 4/5", "1"),
        ("Trục thứ cấp", "1"),
        ("B/răng 1, 2, 3 thứ cấp", "3"),
        ("Trục trung gian", "1"),
        ("B/răng 2, 3 trung gian", "2"),
        ("Bánh răng thường tiếp", "1"),
        ("Trục số de", "1"),
        ("Bánh răng số de", "1"),
        ("Bi rô lê", "1b"),
        ("V/bi trục SC", "1"),
        ("trục TC", "1"),
        ("trục TC", "1"),
        ("trục TG", "1"),
        ("Loa kèn", "1"),
        ("Trục sơ cấp", "1"),
        ("Bộ đồng tốc 1/2", "1"),
        ("trục TG", "1"),
        ("số de", "1"),
        ("Bộ căn phe", "1b")
    ]),
    ("7- CARDAN", [
        ("Thân cardan liền", "1"),
        ("Mặt bích", "2"),
        ("Chữ thập đồng bộ", "3"),
        ("Cao su ổ bi treo+đạn", "1b")
    ]),
    ("8- DẦM CẦU TRƯỚC", [
        ("Vòng bi đùm", "2"),
        ("đùm", "2"),
        ("Mâm bánh xe", "2"),
        ("May ơ bánh xe", "2"),
        ("Jujông tắc kê", "12"),
        ("Đai ốc tắc kê", "12")
    ]),
    ("9- CẦU SAU", [
        ("Bán trục (láp ngang)", "2"),
        ("Bộ vi sai", "1"),
        ("Bánh răng vành chậu", "1"),
        ("côn xoắn", "1"),
        ("Đầu nối cardan", "1"),
        ("Vòng bi vi sai", "2"),
        ("vi sai", "2"),
        ("đùm", "2"),
        ("đùm", "2"),
        ("Mâm bánh xe", "2"),
        ("May ơ bánh xe", "2"),
        ("Jujông tắc kê", "12"),
        ("Đai ốc tắc kê", "12")
    ]),
    ("10- HỆ THỐNG TREO", [
        ("Ống giảm xóc phía trước", "2"),
        ("Thanh đòn ổn định", "1b"),
        ("Rôtuyn treo đứng", "2"),
        ("Gối cao su chống dập phía trước", "2"),
        ("Ống giảm xóc phía sau", "2"),
        ("U quang nhíp sau", "4"),
        ("Gối cao su chống dập phía sau", "2"),
        ("Nhíp sau", "2b")
    ]),
    ("11- KHUNG XE", [
        ("Biển số", "2"),
        ("Cản trước (nhựa)", "1b"),
        ("Bát móc kéo trước", "2"),
        ("Cản sau", "1"),
        ("Vòng móc kéo sau", "1")
    ]),
    ("12- NỘI THẤT", [
        ("La phông trần", "1b"),
        ("Bọc thành trong cửa", "1b"),
        ("Tấm che nắng", "2"),
        ("Bộ đệm ghế", "07"),
        ("Khung ghế", "07"),
        ("Táp bi trải sàn", "1b")
    ]),
    ("13- TRANG BỊ ĐỒNG BỘ", [
        ("Két nước + nắp", "1b"),
        ("Bọc gió két nước", "1"),
        ("Lọc gió", "1"),
        ("Cao su lọc gió", "1"),
        ("Ruột lọc gió", "1"),
        ("Thùng nhiên liệu", "1"),
        ("Nắp thùng nhiên liệu", "1"),
        ("Phao xăng", "1b"),
        ("Lọc nhiên liệu sơ cấp", "1"),
        ("Bô giảm thanh", "1"),
        ("Bộ ống xả", "1b"),
        ("Cao su chắn bùn T+ S", "4"),
        ("Giá lốp dự phòng", "1b"),
        ("Lốp dự phòng", "1b"),
        ("Lốp bánh xe", "4b"),
        ("Đệm chống nóng cabô", "1"),
        ("Tay nắm trần", "5")
    ]),
    ("14- CA BIN, THÂN XE", [
        ("Kính chắn gió", "1"),
        ("Kính chiếu hậu trong", "1"),
        ("Kính chiếu hậu ngoài", "2"),
        ("Tay kính chiếu hậu N", "2"),
        ("Kính hông xe", "4"),
        ("Khóa hãm ngoài", "4"),
        ("Mặt nạ", "1"),
        ("Ca bô", "1"),
        ("Khóa gài cabô", "1b"),
        ("Bệ táp lô nhựa cabin", "1b"),
        ("Khóa hãm trong", "4"),
        ("Cơ cấu khóa cửa", "4"),
        ("Tấm che trong cửa trước", "4"),
        ("Tay nắm trong cửa", "4"),
        ("Tay mỡ trong cửa hông", "4"),
        ("Tay mở ngoài cửa hông", "4"),
        ("Cửa sau xe (1cánh lớn)", "1b"),
        ("Cơ cấu khóa cửa sau", "1"),
        ("Kính cửa sau", "1"),
        ("Tấm che trong cửa sau", "1"),
        ("Tay nắm trong cửa sau", "1"),
        ("Tay mở ngoài cửa sau", "1"),
        ("Joang ống cửa trước", "2"),
        ("Joang ống cưả sau", "2"),
        ("Joang ống cửa cốp sau", "1"),
        ("Joang ống viền cánh cửa", "2")
    ]),
    ("15- HỆ THỐNG LẠNH", [
        ("Máy nén", "1"),
        ("Két dàn nóng", "1"),
        ("Khung bảo vệ két DN", "1"),
        ("Ong dàn lạnh", "4"),
        ("Ong thổi gió dàn lạnh", "5"),
        ("Rờ le", "2"),
        ("Van tiết lưu", "1"),
        ("Timer start", "1"),
        ("Quạt dàn nóng", "1"),
        ("Phin + lọc ga", "1b"),
        ("Dàn lạnh", "2"),
        ("Kim vòi", "2"),
        ("Cảm biến ga", "1"),
        ("Lọc gió dàn lạnh", "1b"),
        ("Cửa gió dàn lạnh trước", "4")
    ]),
    ("16- HỆ THỐNG ÂM THANH", [
        ("Ang ten", "1"),
        ("Catsett", "1")
    ]),
    ("17- TRANG BỊ KHÁC", [
        ("Tem xuất xưởng", "1b"),
        ("Cao su chân máy", "2"),
        ("Cao su chân hộp số", "1"),
        ("Ống nước cao su", "2")
    ])
]

output = {
    "templateVersion": 1,
    "vehicleCode": "FE-SELECT",
    "vehicleName": "Ford Everest",
    "protocolType": "KIEM_CHON",
    "sections": []
}

total_items = 0
for sec_name, sec_items in items:
    section = {"name": sec_name, "items": []}
    for item_name, quantity in sec_items:
        clean_name = re.sub(r'^\s*-\s*', '', item_name)
        clean_name = re.sub(r'^\d+\s*\.?\s*', '', clean_name)
        section["items"].append({
            "name": clean_name,
            "quantity": quantity
        })
        total_items += 1
    output["sections"].append(section)

print(f"Total items extracted: {total_items}")

with open("src/templates/selections/FordEverestSelection.json", "w", encoding="utf-8") as f:
    json.dump(output, f, ensure_ascii=False, indent=2)

