import json
import re

items = [
    ("1.1- TRANG BỊ NGOÀI", [
        ("Cụm hút xả (1H - 2H)", "1"),
        ("Nắp đậy BR cam cơ", "1"),
        ("Nắp che dàn con đội", "2"),
        ("Nắp đậy dàn cò mổ", "1"),
        ("Nắp đổ nhớt", "1"),
        ("Thước đo nhớt", "1"),
        ("Lọc nhớt", "1"),
        ("Lọc xăng tinh", "1b"),
        ("Ruột lọc xăng", "1"),
        ("Ống + rắc co L/xăng", "1b"),
        ("Cánh quạt", "1"),
        ("Cổ ống nước", "1"),
        ("Cao su ống nước", "1b"),
        ("Vỏ trục bộ chia điện", "1"),
        ("Bát bắt lọc xăng", "1"),
        ("Bát bắt lọc gió", "1"),
        ("Bát máy phát", "1"),
        ("Bát câu máy", "1"),
        ("Puly bơm nước", "1"),
        ("Puly trục cơ", "1"),
        ("Đai ốc răng sói", "1"),
        ("Cạc te động cơ", "1"),
        ("Cạc te ly hợp", "1"),
        ("Vỏ bọc bánh đà", "1"),
        ("Tăng cứng bọc B/đà", "2"),
        ("Chân máy trước", "2"),
        ("Khóa nhớt", "1"),
        ("Khóa nước thân máy", "1"),
        ("Ốc tỳ cần bẩy ly hợp", "1"),
        ("Trục bơm", "1"),
        ("Guồng bơm", "1"),
        ("V/bi 20703 + 20803", "2"),
        ("Bộ phớt phíp", "1"),
        ("Vú mỡ bơm nước", "1"),
        ("Bộ ly hợp", "1b"),
        ("Đĩa ép", "1"),
        ("Cần bẩy", "3"),
        ("Quai treo", "3"),
        ("Lò xo đĩa ép", "6"),
        ("Đĩa thép ma sát", "1"),
        ("Bố ma sát", "2"),
        ("Bánh đà", "1"),
        ("Vành răng bánh đà", "1"),
        ("Nắp máy", "1b"),
        ("Trục cò mổ", "1"),
        ("Gối đỡ trục cò mổ", "6"),
        ("Cò mổ", "8"),
        ("Bạc cò mổ", "8"),
        ("Xu páp xả", "4"),
        ("Xu páp hút", "4"),
        ("Xie xu páp hút", "4"),
        ("Xie xu páp xả", "4"),
        ("Ống D/hướng xu páp", "8"),
        ("Lò xo xu páp", "8"),
        ("Đế lò xo", "8"),
        ("Chén chặn xu páp", "8"),
        ("Móng hãm xu páp", "16"),
        ("Đũa đẩy", "8"),
        ("Con đội", "8"),
        ("Trục cam", "1"),
        ("Bạc trục cam", "1b"),
        ("Đệm chặn trục cam", "1"),
        ("Bánh răng cam – cơ", "1b")
    ]),
    ("1.2- CỤM – CHI TIẾT", [
        ("Chế hòa khí 1H - 2H", "1b"),
        ("Bộ cần Đ/khiển ga", "1b"),
        ("Ống + rắc co CHK", "1b"),
        ("Ống CHK → BCĐ", "1b"),
        ("Bơm xăng", "1b"),
        ("Màng da bơm", "1"),
        ("Ống + rắc co B/xăng", "1b"),
        ("Bơm nhớt", "1b"),
        ("Ống + rắc co B/nhớt", "1"),
        ("Bơm nước (đời cu -mới)", "1b"),
        ("Piston", "4"),
        ("Chốt piston", "4"),
        ("Phe gài chốt", "8"),
        ("Vòng găng", "4b"),
        ("Tay biên", "4"),
        ("Bạc thau tay biên", "4"),
        ("Xilanh", "4"),
        ("Thân máy", "1"),
        ("Trục cơ", "1"),
        ("Bạc cổ chính", "1b"),
        ("Bạc cổ biên", "1b"),
        ("Đệm dọc trục", "2"),
        ("Bích chặn trục cơ", "1"),
        ("Vòng chặn nhớt", "1"),
        ("Vòng bi Tr/cơ 6203-Z", "1")
    ]),
    ("1.3- TRANG BỊ ĐIỆN ĐỘNG CƠ", [
        ("Máy khởi động", "1b"),
        ("Bạc thau khởi động", "3"),
        ("Đầu nê khởi động", "1"),
        ("Bánh răng khởi động", "1"),
        ("Rờ le khởi động", "1"),
        ("Than khởi động", "1b"),
        ("Hộp TK", "1"),
        ("Bộ chia điện", "1b"),
        ("Nắp bộ chia điện", "1"),
        ("Con quay chia điện", "1"),
        ("Vít lửa- Mâm bạch kim", "1"),
        ("Tăng điện", "1"),
        ("Nến điện", "4"),
        ("Chụp nến điện", "4"),
        ("Dây phin", "5"),
        ("Cảm biến tO nước TM100", "1"),
        ("AS nhớt M358", "1")
    ]),
    ("2- HỆ THỐNG ĐIỆN", [
        ("Máy phát điện", "1b"),
        ("Puly máy phát", "1"),
        ("Bi MF 180603 + 180502", "2"),
        ("Than máy phát", "2"),
        ("Vỉ tiết chế", "1"),
        ("Hộp điện trở", "1"),
        ("Rờ le đề phụ", "1"),
        ("Bình điện", "1"),
        ("Cọc bình điện", "2"),
        ("Cáp mát + cáp lửa", "2"),
        ("Đồng hồ điện", "1"),
        ("AS nhớt", "1"),
        ("tO nước", "1"),
        ("nhiên liệu", "1"),
        ("tốc độ", "1"),
        ("Dây tốc độ", "1"),
        ("Đèn táp lô", "3"),
        ("Đuôi đèn đồng hồ", "5"),
        ("Tay gạt xi nhan", "1"),
        ("Công tắc điện", "1"),
        ("đèn T/tâm", "1"),
        ("đèn trần", "1"),
        ("đèn tài liệu", "1"),
        ("pha cốt", "1"),
        ("cúp bình", "1"),
        ("10A", "1"),
        ("gạt mưa", "1"),
        ("đèn ưu tiên", "1"),
        ("Buton nhấn còi", "1"),
        ("Còi điện", "1"),
        ("Máy gạt mưa", "1b"),
        ("Bộ thanh chuyền GM", "1b"),
        ("Cần gạt mưa", "2"),
        ("Chổi gạt mưa", "2"),
        ("Đèn pha", "2b"),
        ("Chóa đèn pha", "2"),
        ("Vành đèn pha", "2"),
        ("Bóng đèn pha", "2"),
        ("Đèn hiệu trước", "2"),
        ("hiệu sau", "2"),
        ("hông", "2"),
        ("de", "1"),
        ("trần", "1"),
        ("biển số", "1"),
        ("soi máy", "1"),
        ("đọc tài liệu", "1"),
        ("Cục chớp", "1"),
        ("stop", "1"),
        ("báo de", "1"),
        ("Vú báo đèn nhớt 117", "1"),
        ("Bộ cầu chì xe", "1"),
        ("Cầu chì công tắc T/tâm", "1"),
        ("Bơm ly hợp phụ", "1"),
        ("Rờ le nhiệt", "2"),
        ("Bộ dây điện", "1b"),
        ("CB báo đèn nước 104", "1"),
        ("Bộ rung phòng hỏng", "1"),
        ("ổ cắm diện sau", "1"),
        ("Đèn lách + giá", "1b")
    ]),
    ("3- HỆ THỐNG LÁI", [
        ("Vành TL (N/còi)", "1b"),
        ("Ống tay lái", "1"),
        ("Bi ống tay lái 636905", "2"),
        ("Trục tay lái", "1"),
        ("Khớp nối trục tay lái", "1"),
        ("Hộp cơ cấu lái", "1b"),
        ("Trục vít", "1"),
        ("Cốt trục vít", "1"),
        ("Bi trục vít 77907,908", "2"),
        ("Trục rẻ quạt (C/ngang)", "1"),
        ("Bi trục rẻ quạt 2205", "1"),
        ("Bạc thau hộp tay lái", "1"),
        ("Đòn quay đứng", "1"),
        ("Rô tuyn CH phải + trái", "4"),
        ("Thanh CH dài + ngắn", "2")
    ]),
    ("4- HỆ THỐNG PHANH", [
        ("Bàn đạp (sàn – treo)", "1"),
        ("Bơm phanh cái 1T - 2T", "1"),
        ("Lúp pê bơm phanh", "1"),
        ("Bầu chứa dầu phanh", "2"),
        ("Bầu trợ lực", "1"),
        ("Van hơi hút 1 chiều", "1"),
        ("Bơm phanh con sau", "2"),
        ("Bơm P con trước phải", "2"),
        ("Bơm P con trước trái", "2"),
        ("Tang trống bánh xe", "4"),
        ("Guốc phanh", "8"),
        ("Lò xo G/phanh (4T+2S)", "6"),
        ("Tấm dừng bánh xe", "4"),
        ("Đường ống + rắc co P", "1b"),
        ("Cần kéo phanh", "1"),
        ("Tang trống phanh", "1"),
        ("Guốc phanh tay", "2"),
        ("Lò xo guốc phanh", "2"),
        ("Tấm dừng phanh", "1"),
        ("Cụm chỉnh phanh", "1b")
    ]),
    ("5- DẪN ĐỘNG LY HỢP", [
        ("Bàn đạp (sàn – treo)", "1"),
        ("Bơm ly hợp chính", "1"),
        ("Bầu dầu bơm ly hợp", "1"),
        ("Mặt bích", "2"),
        ("Nắp che bụi cardan", "1"),
        ("Bi tê 6636", "1"),
        ("Ổ trượt bi tê", "1"),
        ("Càng ngắt ly hợp", "1"),
        ("ỐNG MỠ BI TÊ", "1b")
    ]),
    ("6.1- HỘP SỐ CHÍNH", [
        ("Cần số chính", "1"),
        ("Vỏ hộp số", "1"),
        ("Loa kèn", "1"),
        ("Nắp hộp số", "1"),
        ("Nắp 4 lỗ", "1"),
        ("Càng sang số", "3"),
        ("Trục càng sang số", "3"),
        ("Trục sơ cấp", "1"),
        ("Bộ đồng tốc 3/4", "1"),
        ("Vành thau đồng tốc", "2"),
        ("Trục thứ cấp", "1"),
        ("B/răng 1, 2, 3 thứ cấp", "3"),
        ("Trục trung gian", "1"),
        ("B/răng 2, 3 trung gian", "2"),
        ("Bánh răng thường tiếp", "1"),
        ("Trục số de", "1"),
        ("Bánh răng số de", "1"),
        ("Bi rô lê 14.v", "1b"),
        ("Bi trục SC 50208 (6208)", "1"),
        ("TC 50207 (6207)", "1"),
        ("TG 6305", "1"),
        ("TG 50306 (6306)", "1"),
        ("Vòng bi kim", "3"),
        ("Bộ căn phe", "1b")
    ]),
    ("6.2- HỘP SỐ PHỤ", [
        ("Cần gài cầu - số", "2"),
        ("Vỏ hộp số 2 nửa", "1b"),
        ("Nắp cơ cấu gài cầu số", "1"),
        ("Càng gài cầu T - S", "2"),
        ("Trục càng gài cầu T- S", "2"),
        ("Đầu nối cardan trước", "1"),
        ("Trục BR ra cầu trước", "1"),
        ("Trục BR trung gian", "1"),
        ("Trục BR ra cầu sau", "1"),
        ("Bánh răng đôi gài cầu", "1"),
        ("Vòng bi 50306 (6306)", "4"),
        ("50307 (6307)", "1"),
        ("42305", "1"),
        ("Bánh răng tốc độ", "1"),
        ("Trục vít tốc độ", "1"),
        ("Bộ căn phe", "1b")
    ]),
    ("7.1- CARDAN TRƯỚC", [
        ("Đầu then trong", "1"),
        ("Đầu then ngoài", "1"),
        ("Chữ thập đồng bộ", "2"),
        ("Nhíp trước", "2b")
    ]),
    ("7.2- CARDAN SAU", [
        ("Đầu then trong", "1"),
        ("Đầu then ngoài", "1"),
        ("Chữ thập đồng bộ", "2"),
        ("Mặt bích", "2"),
        ("Nắp che bụi cardan", "1")
    ]),
    ("8.1- CẦU TRƯỚC", [
        ("Vỏ cầu dài + ngắn", "2"),
        ("Khớp quay C/hướng", "2"),
        ("Vỏ khớp quayC/hướng", "2"),
        ("Loa kèn đầu cầu", "2"),
        ("Ắc trục đứng + bạc", "4b"),
        ("Ba ngang (bàn tay ếch)", "1"),
        ("Bán trục dài + ngắn", "2"),
        ("Chụp đầu bán trục", "2"),
        ("Bánh răng gài cầu", "2b"),
        ("Bộ vi sai", "1b"),
        ("Bánh răng vành chậu", "1"),
        ("Bánh răng côn xoắn", "1"),
        ("Đầu nối cardan", "1"),
        ("Vòng bi 7510", "2"),
        ("7509", "4"),
        ("102304", "1"),
        ("57707 đôi", "1"),
        ("Mâm bánh xe", "2"),
        ("May ơ bánh xe", "2"),
        ("Jujông + đai ốc tắc kê", "10b"),
        ("Chụp ngoài bánh răng gài cầu", "2")
    ]),
    ("8.2- CẤU SAU", [
        ("Vỏ cầu dài + ngắn", "2"),
        ("Bán trục dài + ngắn", "2"),
        ("Bộ vi sai", "1"),
        ("Bánh răng vành chậu", "1"),
        ("Bánh răng côn xoắn", "1"),
        ("Đầu nối cardan", "1"),
        ("Vòng bi 7510", "2"),
        ("7509", "4"),
        ("102304", "1"),
        ("57707 đôi", "1"),
        ("Mâm bánh xe", "2"),
        ("May ơ bánh xe", "2"),
        ("Jujông + đai ốc tắc kê", "10b")
    ]),
    ("9- HỆ THỐNG TREO", [
        ("Ống giảm xóc", "4"),
        ("Uquang nhíp trước+sau", "8"),
        ("Bát bợ cầu trước+sau", "4"),
        ("Bát nhíp trước + sau", "8"),
        ("Ống đổ thùng N/liệu", "2"),
        ("Phao xăng", "1b"),
        ("Nhíp sau", "2b")
    ]),
    ("10- CA BIN THÂN XE", [
        ("Kính chắn gió (lớn - nhỏ)", "1-2"),
        ("Kính chiếu hậu trong", "1"),
        ("Kính chiếu hậu ngoài", "2"),
        ("Tay kính chiếu hậu N", "2"),
        ("Giá thùng bình điện", "1"),
        ("Móc gài ca bô", "1b"),
        ("Móc giữ ca bô", "1"),
        ("Chống ca bô", "1"),
        ("Cửa hông + cánh gà", "4b"),
        ("Kính cửa hông lùa", "4"),
        ("Kính gió cửa hông -lùa", "4"),
        ("Khóa gài kính gió + lùa", "4"),
        ("Tay nắm cửa", "4"),
        ("Ổ khóa cửa A2 +A1", "4"),
        ("Tay mở cửa ngoài A2+A1", "4"),
        ("Tay mở cửa trong A2 +A1", "4"),
        ("Bửng hậu + khóa gài", "1b"),
        ("Khung kèo mui", "1b"),
        ("Phản quang phía sau", "2")
    ]),
    ("11- NỘI THẤT", [
        ("Bạt mui + kính sau bạt", "1b"),
        ("La phông + táp bi", "1b"),
        ("Tấm che nắng", "2"),
        ("Bộ đệm ghế chính", "5b"),
        ("Bộ đệm ghế phụ", "2b"),
        ("Khung ghế chính", "5b")
    ]),
    ("12- KHUNG XE", [
        ("Biển số", "2"),
        ("Cản trước", "1"),
        ("Móc kéo trước", "2"),
        ("Cản sau", "2"),
        ("Móc hậu", "1")
    ]),
    ("13- TRANG BỊ KHÁC", [
        ("Két nước", "1"),
        ("Nắp két nước", "1"),
        ("Bọc gió két nước", "1"),
        ("Chống két nước", "2"),
        ("Két mát nhớt", "1"),
        ("Dây kéo gió (E)", "1"),
        ("Bầu lọc gió", "1b"),
        ("Ruột lọc gió", "1"),
        ("Thùng nhiên liệu", "2b"),
        ("Nắp thùng NL", "2"),
        ("Khóa xăng sangthùng", "1"),
        ("Lọc xăng sơ cấp", "1"),
        ("Ruột lọc xăng SC", "1"),
        ("Bô giảm thanh", "1"),
        ("Ống bô xả", "1b"),
        ("Giá lốp dự phòng", "1b"),
        ("Vỏ ruột dự phòng", "1b"),
        ("Vỏ ruột bánh xe", "4b")
    ]),
    ("*- CHI TIẾT LẺ PHẦN XE :", [
        ("Khóa nước +khóa nước", "2"),
        ("Nhãn nhôm xuất xưởng", "1b"),
        ("Hướng dẫn đi số", "1b"),
        ("Bầu nước rửa kính+béc phun+ống+buton ấn", "1b"),
        ("Khóa thùng xăng", "2")
    ])
]

output = {
    "templateVersion": 1,
    "vehicleCode": "UAZ31512-SELECT",
    "vehicleName": "UAZ 31512",
    "protocolType": "KIEM_CHON",
    "sections": []
}

total_items = 0
for sec_name, sec_items in items:
    section = {"name": sec_name, "items": []}
    for item_name, quantity in sec_items:
        clean_name = re.sub(r'^\s*-\s*', '', item_name)
        clean_name = re.sub(r'^\d+\s*\.?\s*', '', clean_name)
        section["items"].append({
            "name": clean_name,
            "quantity": quantity
        })
        total_items += 1
    output["sections"].append(section)

print(f"Total items extracted: {total_items}")

with open("src/templates/selections/UAZ31512Selection.json", "w", encoding="utf-8") as f:
    json.dump(output, f, ensure_ascii=False, indent=2)

